### ISSUE TITLE
CalDAV: Sync colors after setup

### ISSUE THREAD

**Issue by stefan-niedermann** [bitfireAT/davdroid#136]
If i change the colors of a calendar in my ownCloud they get not synced to the client.

**Comment by untitaker** [comment]
I think this can be closed.

**Comment by rfc2822** [comment]
Thanks for the hint, closing

**Comment by untitaker** [comment]
I'm starting to use DAVDroid and wanted to know: How is the current behavior regarding color sync? Does it still download the colors at setup time?

**Comment by rfc2822** [comment]
> Does it still download the colors at setup time?

Yes: At the moment, colors are only [fetched here](https://github.com/bitfireAT/davdroid/blob/c3f7c1b97ef734b4c33375c858ba9bfac0f5709c/app/src/main/java/at/bitfire/davdroid/resource/DavResourceFinder.java) from the PROPFIND response, then put into `ServerInfo.ResourceInfo` and then later used when creating the `LocalCollection`s.

**Comment by untitaker** [comment]
I suppose a manually triggered re-discovery of all collections would fix this issue (as well as add the ability to sync new collections). See CalDAV-Sync for what I mean.

**Comment by rfc2822** [comment]
> I suppose a manually triggered re-discovery of all collections would fix this issue (as well as add the ability to sync new collections).

Please follow up in in #219 and #243 for that.

> See CalDAV-Sync for what I mean.

As far as I know, CalDAV-Sync is not open-source? So unfortunately, I can't see how it's handled there.

**Comment by untitaker** [comment]
>As far as I know, CalDAV-Sync is not open-source? So unfortunately, I can't see how it's handled there.

I meant how it is implemented UI-wise: Part of collection discovery, which doesn't happen regularly but has to be triggered manually.

**Comment by rfc2822** [comment]
> I meant how it is implemented UI-wise: Part of collection discovery, which doesn't happen regularly but has to be triggered manually.

Ah ok, this is #219. Please follow up there.

I don't know when this will be done, at the moment I'm happy about tasks sync :)
