### ISSUE TITLE
Process exceptions of recurring events

### ISSUE THREAD

**Issue by michaelweghorn** [bitfireAT/davdroid#170]
I am using DAVdroid 0.5.7-alpha on Cyanogenmod 10.2.1.

When I change only one occurence of a repeating event in Thunderbird, the changes are not synchronized correctly to my smartphone's calendar.

Steps I take:
- create a repeating event in the CalDAV calendar using Icedove 17.0.10/Iceowl 1.9b1 (the Debian versions of Thunderbird/Lightning) with two occurences and give the event the title "TestEvent"
- synchronize calendar using DAVdroid
-  change the title of the second occurence to "NewTitle" in Icedove/Iceowl
- synchronize calendar using DAVdroid
- result: the change is not synchronized and the title which is displayed on my Android calendar remains "TestEvent" for both occurences of the event

(In another instance of Icedove/Iceowl, the title of the second occurence is synchronized correctly and changes to "NewTitle").

logcat output of first DAVdroid synchronization (after creating the repeating event):

I/davdroid.SyncManager(12369): Fetching 1 new remote resource(s)
D/davdroid.WebDavResource(12369): Received HTTP/1.1 200 OK
D/davdroid.WebDavResource(12369): BEGIN:VCALENDAR
D/davdroid.WebDavResource(12369): PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
D/davdroid.WebDavResource(12369): VERSION:2.0
D/davdroid.WebDavResource(12369): BEGIN:VTIMEZONE
D/davdroid.WebDavResource(12369): TZID:Europe/Berlin
D/davdroid.WebDavResource(12369): X-LIC-LOCATION:Europe/Berlin
D/davdroid.WebDavResource(12369): BEGIN:DAYLIGHT
D/davdroid.WebDavResource(12369): TZOFFSETFROM:+0100
D/davdroid.WebDavResource(12369): TZOFFSETTO:+0200
D/davdroid.WebDavResource(12369): TZNAME:CEST
D/davdroid.WebDavResource(12369): DTSTART:19700329T020000
D/davdroid.WebDavResource(12369): RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
D/davdroid.WebDavResource(12369): END:DAYLIGHT
D/davdroid.WebDavResource(12369): BEGIN:STANDARD
D/davdroid.WebDavResource(12369): TZOFFSETFROM:+0200
D/davdroid.WebDavResource(12369): TZOFFSETTO:+0100
D/davdroid.WebDavResource(12369): TZNAME:CET
D/davdroid.WebDavResource(12369): DTSTART:19701025T030000
D/davdroid.WebDavResource(12369): RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
D/davdroid.WebDavResource(12369): END:STANDARD
D/davdroid.WebDavResource(12369): END:VTIMEZONE
D/davdroid.WebDavResource(12369): BEGIN:VEVENT
D/davdroid.WebDavResource(12369): CREATED:20140207T211000Z
D/davdroid.WebDavResource(12369): LAST-MODIFIED:20140207T211027Z
D/davdroid.WebDavResource(12369): DTSTAMP:20140207T211027Z
D/davdroid.WebDavResource(12369): UID:f8973465-a13b-4ea8-be97-a7a52c0d4c09
D/davdroid.WebDavResource(12369): SUMMARY:TestEvent
D/davdroid.WebDavResource(12369): RRULE:FREQ=DAILY;COUNT=2
D/davdroid.WebDavResource(12369): DTSTART;TZID=Europe/Berlin:20140218T100000
D/davdroid.WebDavResource(12369): DTEND;TZID=Europe/Berlin:20140218T110000
D/davdroid.WebDavResource(12369): END:VEVENT
D/davdroid.WebDavResource(12369): END:VCALENDAR
D/davdroid.Event(12369): Assuming time zone Europe/Berlin for Europe/Berlin
D/davdroid.Event(12369): Assuming time zone Europe/Berlin for Europe/Berlin
D/davdroid.SyncManager(12369): Adding f8973465-a13b-4ea8-be97-a7a52c0d4c09.ics
D/davdroid.LocalCollection(12369): Committing 1 operations
I/davdroid.SyncManager(12369): Fetching 0 updated remote resource(s)
I/davdroid.SyncManager(12369): Removing non-dirty resources that are not present remotely anymore
D/davdroid.LocalCollection(12369): Committing 1 operations
I/davdroid.SyncManager(12369): Sync complete, fetching new CTag
D/davdroid.LocalCollection(12369): Committing 1 operations

logcat output of second synchronization (after changing title of the second occurence to "NewTitle"):

I/davdroid.SyncManager(12369): Fetching 0 new remote resource(s)
I/davdroid.SyncManager(12369): Fetching 1 updated remote resource(s)
D/davdroid.WebDavResource(12369): Received HTTP/1.1 200 OK
D/davdroid.WebDavResource(12369): BEGIN:VCALENDAR
D/davdroid.WebDavResource(12369): PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
D/davdroid.WebDavResource(12369): VERSION:2.0
D/davdroid.WebDavResource(12369): BEGIN:VTIMEZONE
D/davdroid.WebDavResource(12369): TZID:Europe/Berlin
D/davdroid.WebDavResource(12369): X-LIC-LOCATION:Europe/Berlin
D/davdroid.WebDavResource(12369): BEGIN:DAYLIGHT
D/davdroid.WebDavResource(12369): TZOFFSETFROM:+0100
D/davdroid.WebDavResource(12369): TZOFFSETTO:+0200
D/davdroid.WebDavResource(12369): TZNAME:CEST
D/davdroid.WebDavResource(12369): DTSTART:19700329T020000
D/davdroid.WebDavResource(12369): RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
D/davdroid.WebDavResource(12369): END:DAYLIGHT
D/davdroid.WebDavResource(12369): BEGIN:STANDARD
D/davdroid.WebDavResource(12369): TZOFFSETFROM:+0200
D/davdroid.WebDavResource(12369): TZOFFSETTO:+0100
D/davdroid.WebDavResource(12369): TZNAME:CET
D/davdroid.WebDavResource(12369): DTSTART:19701025T030000
D/davdroid.WebDavResource(12369): RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
D/davdroid.WebDavResource(12369): END:STANDARD
D/davdroid.WebDavResource(12369): END:VTIMEZONE
D/davdroid.WebDavResource(12369): BEGIN:VEVENT
D/davdroid.WebDavResource(12369): CREATED:20140207T211000Z
D/davdroid.WebDavResource(12369): LAST-MODIFIED:20140207T211159Z
D/davdroid.WebDavResource(12369): DTSTAMP:20140207T211159Z
D/davdroid.WebDavResource(12369): UID:f8973465-a13b-4ea8-be97-a7a52c0d4c09
D/davdroid.WebDavResource(12369): SUMMARY:TestEvent
D/davdroid.WebDavResource(12369): RRULE:FREQ=DAILY;COUNT=2
D/davdroid.WebDavResource(12369): DTSTART;TZID=Europe/Berlin:20140218T100000
D/davdroid.WebDavResource(12369): DTEND;TZID=Europe/Berlin:20140218T110000
D/davdroid.WebDavResource(12369): X-MOZ-GENERATION:1
D/davdroid.WebDavResource(12369): END:VEVENT
D/davdroid.WebDavResource(12369): BEGIN:VEVENT
D/davdroid.WebDavResource(12369): CREATED:20140207T211150Z
D/davdroid.WebDavResource(12369): LAST-MODIFIED:20140207T211159Z
D/davdroid.WebDavResource(12369): DTSTAMP:20140207T211159Z
D/davdroid.WebDavResource(12369): UID:f8973465-a13b-4ea8-be97-a7a52c0d4c09
D/davdroid.WebDavResource(12369): SUMMARY:NewTitle
D/davdroid.WebDavResource(12369): RECURRENCE-ID;TZID=Europe/Berlin:20140219T100000
D/davdroid.WebDavResource(12369): DTSTART;TZID=Europe/Berlin:2…
D/davdroid.Event(12369): Assuming time zone Europe/Berlin for Europe/Berlin
D/davdroid.Event(12369): Assuming time zone Europe/Berlin for Europe/Berlin
I/davdroid.SyncManager(12369): Updating f8973465-a13b-4ea8-be97-a7a52c0d4c09.ics
D/davdroid.LocalCollection(12369): Committing 3 operations
I/davdroid.SyncManager(12369): Removing non-dirty resources that are not present remotely anymore
D/davdroid.LocalCollection(12369): Committing 1 operations
I/davdroid.SyncManager(12369): Sync complete, fetching new CTag
D/davdroid.LocalCollection(12369): Committing 1 operations

The calendar is hosted on fruux.com.

**Comment by rfc2822** [comment]
Results of today's reading:

* The recurring "master" event and all its exceptions share the same UID. The exceptions have a RECURRING-ID that shows which of the event instances is overriden by the exception.
* All VEVENTs with the same UID (i.e. the master event + its exceptions) have to be in the same .ics file on CalDAV servers.

**Comment by k21735** [comment]
Hello,
I am also willing to make a donation for this enhancement (and for full support of the iCalendar RFC). As far as I am concerned this bug unfortunately makes DAVdroid completely unusable!

**Comment by rfc2822** [comment]
Can you try with 0.7.3 (will be in the stores soon)? Please also read https://davdroid.bitfire.at/faq/entry/recurring-events

**Comment by rfc2822** [comment]
> I am also willing to make a donation for this enhancement (and for full support of the iCalendar RFC).

BTW: While testing, I haven't seen *any* working implementation with full support of the iCalendar RFC, even iCloud fails and crashes if you play around too much in the Web GUI (just try adding a recurring event, then moving around single instances, deleting them, switching between all-day and date-time, etc.).

**Comment by rfc2822** [comment]
Basic support has been implemented with 0.7.3. For mre specific issues, please create a new ticket with verbose information.

**Comment by phmarek** [comment]
well, what would you need?
I installed git HEAD yesterday (reading the release notes), and even removed the account and re-created it...
but exceptions are still not handled correctly.

(eg. a recurring event that has a few dates removed is still shown all the time.)

**Comment by rfc2822** [comment]
Please provide detailed instructions on how to reproduce in a separate issue. Please also read https://davdroid.bitfire.at/faq/entry/recurring-events
