### ISSUE TITLE
Please add sync for contact field "relationship"

### ISSUE THREAD

**Issue by mirko2324** [bitfireAT/davdroid#278]
Can you please add the field "relationship" in contacts? Actually I can't add this information to an contact that will be synced with davdroid.

**Comment by equaeghe** [comment]
I use that all the time... or actually, whenever I use a client that supports it. This is actually still one of the reasons I also keep CardDAV-Sync installed, to have access to these fields.

In vCard 3 files, they seem to be implemented as, e.g.,

```
ITEM5.X-ABRELATEDNAMES:John Doe
ITEM5.X-ABLABEL:_$!<Brother>!$_
```

It's useful, for example, to keep tabs on all the names of the partners and children of friends and family.

**Comment by rfc2822** [comment]
> In vCard 3 files, they seem to be implemented as, e.g.,

This is a proprietary implementation. VCard 3 doesn't define relationship at all – but it would be interesting to know how different services map this field. Basically, it's the same problem as #426 because one could just use the VCard 4 properties in VCard 3 files, too.

**Comment by equaeghe** [comment]
Well, the `ITEM5.` prefix is standard vCard grouping, which I guess you know, semantically abused to link both. The part after that is what I got in Google contacts-exported vCards. It seems this is (was?) a subset of the custom Apple properties (http://stackoverflow.com/questions/14002688/can-i-create-relationships-between-vcards-on-a-carddav-server, http://www.w3.org/2002/12/cal/vcard-notes.html).

Of what I know, Clients that use this are CardDavMATE (https://www.inf-it.com/open-source/clients/carddavmate/), CardDav-Sync. ownCloud does not support this, neither does Horde (default setup), and KDE 4.14. I have not come accross other conventions for this, but I have not surveyed much.

Would using that as a read-only property be possible? But perhaps this would cause confusion because the android clients would allow it to be edited?

**Comment by promeneur** [comment]
if this can help this the result of my investigation

kaddressbook 4.14.4 + akonadi google connector : 
- Vcard 3.0
- X-KADDRESSBOOK-X-SpousesName 
- X-KADDRESSBOOK-X-AssistantsName

kaddressbook 4.14.4 + akonadi carddav connector : 
- Vcard 3.0
- X-KADDRESSBOOK-X-SpousesName 
- X-KADDRESSBOOK-X-AssistantsName

google contacts : 
- Vcard 3.0
- item1.X-ABRELATEDNAMES
- item1.X-ABLabel:_$!<Assistant>!$_
- item1.X-ABRELATEDNAMES
- item1.X-ABLabel:_$!<Spouse>!$_

android 4.2.2 samsung contacts + google count manages fields : 
- Assistant
- Spouse

owncloud contacts 0.3.0.18 uses vcard 3.0 , stores and ignores the statements : 
- X-KADDRESSBOOK-X-SpousesName 
- X-KADDRESSBOOK-X-AssistantsName

**Comment by equaeghe** [comment]
Watch out with KAddressbook, it *deletes* fields it does not know when you modify an entry! The same happens with Thunderbird+SOGO connector and multiple email addresses and phone numbers.

OwnCloud doesn't touch fields it does not know; it has no support for X-KADDRESSBOOK or X-AB... specials but leaves them alone.

N.B.: I assume that for ‘Spouse’ `item1` there and on the line above needs to be changed to `item2`. Also, you need to check/edit your MarkDown: `<Assistant>` and `<Spouse>` are visible in the mail I got, but not in the web version on GitHub.

**Comment by promeneur** [comment]
there is a pb with github editor : 
the part between $! and !$ disappears and also the final _
so i rewrite it by adding blanks
i t e m 1 . X - A B L a b e l : _ $ ! < A s s i s t a n t > ! $ _
i t e m 1 . X - A B L a b e l : _ $ ! < S p o u s e > ! $ _

**Comment by promeneur** [comment]
>> item1 
 there are two occurences of item1 because i extract them from 2 different cards

>> Watch out with KAddressbook, it deletes fields it does not know when you modify an entry!

can you explain in detail please ?

**Comment by equaeghe** [comment]
That is not a problem with the editor, it uses Markdown. (See “Markdown supported” at the top of the editor). A workaround is to format things as inline code (which is actually reasonable): `item1.X-ABLabel_$!<whatever>!$_`.

Regarding KAddressbook: well, there is not much to explain; if you have an entry with a field that KAddressbook does not know, and you edit that entry with KAddressbook, then in my experience, KAddressbook silently *removes* that field.

**Comment by promeneur** [comment]
i don't understand .
if kaddressbook don't know about a field how it can supply it to you for editing ?
have you an example of these field ?
thanks

**Comment by equaeghe** [comment]
KAddressbook can access CardDAV resources. Those you can also edit with other CardDAV clients to enter fields unknown to KAddressbook. For example the `item1.X-AB...` fields get removed.

**Comment by rfc2822** [comment]
Which address book app do you use? I can't find any that actually shows Relationships.

**Comment by rfc2822** [comment]
Free-from relations are now supported, but only in the VCard 4.0 way:
```
RELATED;TYPE=child;VALUE=text:Child name
```

At the moment, only (free-from) "text" values are supported (not supported: email addresses, URIs).

If the server supports VCard 4.0, it should understand that. Please note that when testing, we have found some servers that say to accept VCard 4.0, but all of them had problems handling such relations. Some accepted and processed the RELATED properties correctly, but converted them into X-CHILDREN etc., while other servers just ignored the field.

If the server doesn't accept VCard 4.0 (you can check in the DAVdroid account settings), RELATED will still be sent but VCard 3.0 doesn't define RELATED so you can't expect it to work.

DAVdroid won't support undocumented X- types for relations. If you have problems with your server, please check whether the VCards are processed by the server correctly and whether your server sends valid version 4.0 VCards before filing bugs.
