### ISSUE TITLE
Sync tasks

### ISSUE THREAD

**Issue by lemmy** [bitfireAT/davdroid#34]
Please add support for task syncing.

**Comment by varac** [comment]
@rfc2822: i see this is the only open issue on the next milestone - when do you expect to release it ?

**Comment by devvv4ever** [comment]
We've already discussed this in more detail internally, however this is more complex than we expected in early days of DAVdroid. The milestones need to be adjusted - they don't reflect the current plan. 

There also needs to be re-coding some of our core components. But be asured, we will be getting there... Tasks are still a high priority feature that we want to get in. But first we have to introduce a basic settings dialogue which will be the next (bigger) feature for DAVdroid (which is also necessary for future features like tasks).

I've attached an image that illustrates the sync process and the involved components and how they play together. Tasks are also part of it, but since there is no standard storage for tasks it's hard for DAVdroid to hook in at a certain position.
![how_davdroid_works](https://cloud.githubusercontent.com/assets/3578887/6287845/f5f6ba90-b914-11e4-9b5e-d53eb0d3e0b9.png)

**Comment by untitaker** [comment]
I know it's easy for me to talk, but I'm sure both the Mirakel devs and dmfs have the same goals, which is why I think it'd be in everybody's interest to unify both task providers, no?

**Comment by untitaker** [comment]
Also, what in iCalendar would you use to represent notes?

**Comment by devvv4ever** [comment]
It's not just Mirakel and dmfs... In a more general way of thinking it would be the best to have a standardized backend which can be used by different sync apps. It was always our intention to be an app that is compatible with a lot of services. A very nice solution would be a new generalized tasks storage app/proxy which DAVdroid could use to sync data instead of making workarounds for different apps that provide tasks. 

At the moment (we've *not* finished thinking about it!) we'd use VJOURNAL for notes and VTODO for tasks.

**Comment by untitaker** [comment]
Thanks for your answer. I think a general-purpose task storage is/was @dmfs' goal.

**Comment by accuraz** [comment]
+1 for me...

**Comment by gour** [comment]
I'd like to be able to use DAVdroid with Mirakel or something else to sync my org-mode tasks which already work for my calendars and I'm just about to configure it for the contacts, so

+1

**Comment by Whisprin** [comment]
The developer of CalDAV-Sync (which has working task sync) started open-sourcing parts of the app. You can find the DAV framework here: https://github.com/dmfs/jdav
Maybe it's helpful.

**Comment by rfc2822** [comment]
Finally implemented in 0.8.0. Can you please test it?

**Comment by ways** [comment]
Ha ha! Issue created 21 Oct 2013. That took some time (not complaining, though!). I can't wait to test. My current todo setup is falling apart.

**Comment by CiaranG** [comment]
Woah! I don't like spamming issues, but I'm making an exception because this is the best news I've heard in a long time. THANK YOU! (now to test...)

**Comment by weiznich** [comment]
Seems like the current implementation will only work with dmfs-tasks, not mirakel.

**Comment by HLFH** [comment]
@rfc2822 You made my day. It fully works. Tested with dmfs-tasks. Thanks a lot. 0.8.0 could be renamed to 1.0

**Comment by untitaker** [comment]
It works but DAVDroid seems to reorder properties of my ics files quite liberally, delete unneeded timezones and change the PRODID to one of its own.

**Comment by rfc2822** [comment]
> It works but DAVDroid seems to reorder properties of my ics files quite liberally, delete unneeded timezones and change the PRODID to one of its own.

The iCalendar object is first (lossfully) transferred into the Tasks database, then re-created from the database again and uploaded. PRODID "specifies the identifier for the product that created the iCalendar object", so I guess that should be set to DAVdroid.

I don't see a problem here, but feel free to open a new issue when something doesn't work. Please not that the Tasks provider supports only one time-zone for the whole task.

**Comment by untitaker** [comment]
>PRODID "specifies the identifier for the product that created the iCalendar object"

Well yeah, if the iCalendar file is not really preserved I guess you can say that DAVDroid created it.

The (minor) problem is IMO that DavDroid seems to re-upload those "changed" items even if I didn't modify them with the Tasks app.

**Comment by rfc2822** [comment]
> The (minor) problem is IMO that DavDroid seems to re-upload those "changed" items even if I didn't modify them with the Tasks app.

This should not happen and does not happen here.

**Comment by devvv4ever** [comment]
weiznich: don't worry, Mirakel is on the scope to be included, if everything works and maybe even priorized above dmfs tasks then ;-)

**Comment by onny** [comment]
Seems also to work fine here for me. This version is a huge step forward, thank you for your work!

**Comment by untitaker** [comment]
No idea if possible, but why not implement the dmfs interface in Mirakel instead and make everything work with everything else?

**Comment by weiznich** [comment]
@It's already implemented in this way. The only thing left is the check which app is installed and then choose the corresponding Uri to reach this app.
This will be done as soon as someone from the Mirakel team has some time to check the sync before.

**Comment by awikatchikaen** [comment]
for me, davdroid crash when i click for tasks synchronization.

**Comment by untitaker** [comment]
@awikatchikaen Please take a look at [How to view the logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs). A possibility not mentioned there is CatLog (requires root).

**Comment by awikatchikaen** [comment]
E/AndroidRuntime( 8769): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime( 8769): Process: at.bitfire.davdroid:sync, PID: 8769
E/AndroidRuntime( 8769): java.lang.SecurityException: Permission Denial: opening provider org.dmfs.provider.tasks.TaskProvider from ProcessRecord{42bf44f8 8769:at.bitfire.davdroid:sync/u0a175} (pid=8769, uid=10175) requires org.dmfs.permission.READ_TASKS or org.dmfs.permission.WRITE_TASKS
E/AndroidRuntime( 8769): 	at android.os.Parcel.readException(Parcel.java:1465)
E/AndroidRuntime( 8769): 	at android.os.Parcel.readException(Parcel.java:1419)
E/AndroidRuntime( 8769): 	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2887)
E/AndroidRuntime( 8769): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4480)
E/AndroidRuntime( 8769): 	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2308)
E/AndroidRuntime( 8769): 	at android.content.ContentResolver.acquireProvider(ContentResolver.java:1409)
E/AndroidRuntime( 8769): 	at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:1472)
E/AndroidRuntime( 8769): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
D/davdroid.DavSyncAdapter( 8769): Closing httpClient

**Comment by untitaker** [comment]
@awikatchikaen I think your problem is that you didn't install the Tasks app before the DavDroid app. Or something else is limiting DavDroid's permissions (Xprivacy or CyanogenMod Privacy Guard)

**Comment by awikatchikaen** [comment]
Yes I've install davdroid some months ago.
And I install tasks app some day ago to test task synchronization.

And, frankly, I don't want deinstall and reinstall davdroid and redo the configuration ....

**Comment by untitaker** [comment]
There's no other way, it's a bug in Android. There are many apps to save and restore app data, such as Titanium Backup or oandbackup.

**Comment by rfc2822** [comment]
Implemented with 0.8.
