### ISSUE TITLE
Incorrect offset for Europe/Moscow TZ

### ISSUE THREAD

**Issue by kernins** [bitfireAT/davdroid#379]
It is better explained on example:
- created event on the phone, 7:00-8:00 MSK (+03:00)
- corresponding row in calendar.db Events table has correct timestamps (1417320000 - 1417323600) and timezone (Europe/Moscow)
- but owncloud shows 8:00-9:00 MSK in UI, 5:00 - 6:00 GMT in database (should be 4:00-5:00 GMT)

My phone and server has correct settings and updated tzdata, no other apps I'm using has tz-related issues.

There was some changes in Russian DST rules recently, previously MSK was +4, now it is +3. If DAVDroid still threats Europe/Moscow as +4, it would be exaclty +1 hour, as observed

May be related to 
>I have disabled the auto-update feature (successfully I hope).

and also indicates that system tzdata not used by DAVDroid

**Comment by rfc2822** [comment]
Reported to upstream: https://github.com/ical4j/ical4j/issues/24
Please follow up there.

**Comment by Pastafarianist** [comment]
The upstream has closed the bug, yet the most recent release of DAVDroid still has it. What's wrong?

**Comment by rfc2822** [comment]
There has been no new ical4j release, as far as I know.

**Comment by rfc2822** [comment]
Merged with #509, please follow up there.

**Comment by Pastafarianist** [comment]
Thank you for the update. Waiting for a release then!
