### ISSUE TITLE
Syncing calendar not working

### ISSUE THREAD

**Issue by siccegge** [bitfireAT/davdroid#393]
Hi!

I have problems syncing with my online calendar. It may be somewhat related to `@` signs in resource names. Setup is nginx->uwsgi->radicale (0.9) on the server

korganizer and thunderbird / lighning seem to work just fine with the same calendar

Christoph

Nginx log:

    2001::XXXX - christoph [16/Dec/2014:14:55:43 +0100] "PROPFIND /christoph/calendar/ HTTP/1.1" 207 148689 "-" "DAVdroid/0.6.8"
    2001::XXXX - christoph [16/Dec/2014:14:55:50 +0100] "REPORT /christoph/calendar/ HTTP/1.1" 207 50 "-" "DAVdroid/0.6.8"

UWSGI log

    [pid: 2872|app: 0|req: 5/5] 2001::XXXX () {44 vars in 669 bytes} [Tue Dec 16 14:55:42 2014] PROPFIND /christoph/calendar/ => generated 148689 bytes in 628 msecs (HTTP/1.1 207) 3 headers in 132 bytes (1 switches on core 0)
    [pid: 2872|app: 0|req: 6/6] 2001::XXXX () {44 vars in 669 bytes} [Tue Dec 16 14:55:50 2014] REPORT /christoph/calendar/ => generated 50 bytes in 129 msecs (HTTP/1.1 207) 2 headers in 68 bytes (1 switches on core 3)

adb logcat

    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/U-8wOAtiUft8JjHbW-HAEA%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/NzaYFnLUYCWw9gjG_KMgsQ@frab.cccv.de -> /christoph/calendar/NzaYFnLUYCWw9gjG_KMgsQ%40frab.cccv.de
    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/NzaYFnLUYCWw9gjG_KMgsQ%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/EeC2O7AUgtd_O02jxngVxQ@frab.cccv.de -> /christoph/calendar/EeC2O7AUgtd_O02jxngVxQ%40frab.cccv.de
    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/EeC2O7AUgtd_O02jxngVxQ%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/H9UerBUbMiZgVzVzcpYRFQ@frab.cccv.de -> /christoph/calendar/H9UerBUbMiZgVzVzcpYRFQ%40frab.cccv.de
    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/H9UerBUbMiZgVzVzcpYRFQ%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/4edFJcqsY3ORA5pyBrkthA@frab.cccv.de -> /christoph/calendar/4edFJcqsY3ORA5pyBrkthA%40frab.cccv.de
    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/4edFJcqsY3ORA5pyBrkthA%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/tbP0pE8M3Do-9jVyC04sXg@frab.cccv.de -> /christoph/calendar/tbP0pE8M3Do-9jVyC04sXg%40frab.cccv.de
    D/davdroid.WebDavResource( 8304): Processing multi-status element: https://pim.siccegge.de/christoph/calendar/tbP0pE8M3Do-9jVyC04sXg%40frab.cccv.de
    W/davdroid.URIUtils( 8304): Trying to repair invalid URL: /christoph/calendar/k3OMz1miLcDM6BdSbXanKw@frab.cccv.de -> /christoph/calendar/k3OMz1miLcDM6BdSbXanKw%40frab.cccv.de
    ...
    I/davdroid.SyncManager( 8304): Fetching 50 new remote resource(s)
    I/davdroid.RemoteCollection( 8304): Multi-getting 35 remote resource(s)
    E/WifiStateMachine( 1800): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=48.13 rxSuccessRate=54.61 targetRoamBSSID=any RSSI=-80
    E/davdroid.DavSyncAdapter( 8304): Invalid DAV response
    E/davdroid.DavSyncAdapter( 8304): at.bitfire.davdroid.webdav.DavNoContentException: Invalid DAV response: HTTP response entity (content) expected but not received
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.webdav.WebDavResource.processMultiStatus(WebDavResource.java:452)
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.webdav.WebDavResource.multiGet(WebDavResource.java:325)
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.resource.RemoteCollection.multiGet(RemoteCollection.java:93)
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:191)
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:88)
    E/davdroid.DavSyncAdapter( 8304): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:134)
    E/davdroid.DavSyncAdapter( 8304): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
    I/davdroid.DavSyncAdapter( 8304): Sync complete for com.android.calendar
    D/SyncManager( 1800): failed sync operation christoph@pim.siccegge.de u0 (bitfire.at.davdroid), com.android.calendar, USER, currentRunTime 2027012, EXPEDITED, reason: 10006, SyncResult: stats [ numParseExceptions: 1]
    D/davdroid.DavSyncAdapter( 8304): Closing httpClient

**Comment by rfc2822** [comment]
Can you try again with 0.6.10.1?
