### ISSUE TITLE
Sync is currently experiencing problems. It will be back shortly.

### ISSUE THREAD

**Issue by robertzach** [bitfireAT/davdroid#397]
I get the error message "Sync is currently experiencing problems. It will be back shortly." (In german "Bei der Synchronisierung treten momentan Probleme auf. Sie wird in Kürze fortgesetzt.").
Server is Baikal 0.2.7 working fine with Outlook Bynari Plugin, etc.
Latest Cyagenmod on Nexus 5.

Any Idea? Workaround?
I found this on the play store:
https://play.google.com/store/apps/details?id=ru.ivary.ContactsSyncFix
This app does not find any broken contacts...

Thanks in advance for your help!

**Comment by rfc2822** [comment]
Any news on this?
