### ISSUE TITLE
FastMail sync not working

### ISSUE THREAD

**Issue by p3lim** [bitfireAT/davdroid#399]
I'm trying to sync my calendars to FastMail without success, using CalDAV-Sync (competitor) works fine.

**Comment by devvv4ever** [comment]
We've just tested everything with current master of DAVdroid and it seems to work great - both CalDAV and CardDAV.

**Comment by rfc2822** [comment]
@p3lim Does it work for you, too?

**Comment by p3lim** [comment]
@rfc2822 Sorry for the late reply, never saw the mention.

Yes, it works for me as well, thanks.
