### ISSUE TITLE
Sync (0.6.7) fails when server (Owncloud) response is 3MB

### ISSUE THREAD

**Issue by jensb** [bitfireAT/davdroid#404]
I am syncing my Galaxy S5 (Android 4.4.4) to an Owncloud 7 installation using DAVdroid 0.6.7-mirakel (I need the tasks support). Syncing calendars and tasks works fine, but syncing my contacts fails although the server (correctly) responds with a HTTP 207 response.

Is it possible that DAVdroid cannot cope with the size of the response (about 3MB, contains a lot of encoded contact images)? I am watching the conversation using MITMproxy and everything seems to be fine.

EDIT: Also I notice that every time I restart sync, the number of contacts on my phone increases by about 5..10 contacts. So it is actually doing something but failing anyway.

**Comment by rfc2822** [comment]
Any news on this?
