### ISSUE TITLE
No need for a notification "Synchronization failed"

### ISSUE THREAD

**Issue by newluck77** [bitfireAT/davdroid#409]
Hello!

Since updating to DAVdroid 0.6.10 there is a notification in my notification bar, which says "Synchronization failed" along with exceptions. However I would like to turn these notifications off as I am aware that, when my server is not running, there won't be any syncing.

Cheers!

My setup: Owncloud in a VirtualBox only accessible in the home network and only, when my host PC is running.

**Comment by markus80** [comment]
"Every feature you cannot configure is a bug." ;)

**Comment by newluck77** [comment]
I'd call my post a feature request. ;)
Unfortunately, I cannot add labels, as far as I know... :(

**Comment by devvv4ever** [comment]
You can switch off automatic sync on the DAVdroid account. Then the notifications won't appear on your phone.

**Comment by FabianGr** [comment]
I'd really love to be able to turn off those notifications again, too.

Switching off automatic sync is not an option for me. Before 0.6.10 DAVDroid just silently failed when the hostname of the server was not resolvable. That was great behaviour and one of the resons I chose DAVDroid in the first place. I'd like that behaviour back.

**Comment by untitaker** [comment]
FWIW newer versions of Android can block a specific kind of notification, or disable notifications per-app.

**Comment by FabianGr** [comment]
Thanks for that hint, Markus.

**Comment by devvv4ever** [comment]
Thanks! I'll close this. 

For everyone else: You can switch off notifications by going to 
Settings / Apps / DAVdroid - then uncheck the "Show notifications" option.

**Comment by newluck77** [comment]
Thanks for the solution!
