### ISSUE TITLE
401 unauthorized on contacts sync

### ISSUE THREAD

**Issue by shiba89** [bitfireAT/davdroid#416]
Since 0.6.10.x (F-Droid) if I edit a contact I am no longer able to sync, with error 401 unauthorized. Downgrading to 0.6.8 solve this.
![screenshot_2015-01-07-10-48-16](https://cloud.githubusercontent.com/assets/3816409/5643677/a098d3a2-965b-11e4-8b72-53e201ac11e9.png)

**Comment by devvv4ever** [comment]
We need verbose logs from your phone to look into this issue please. Here is a small tutorial on how you get these logs. https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by rfc2822** [comment]
Is there a reason why you think this is a client problem? 401 means Unauthorized, i.e. wrong user name/password. Maybe the password has changed?

**Comment by shiba89** [comment]
@rfc2822 it's my private server :)
@devvv4ever thank you, maybe I will try this weekend, I don't have much time right now.

**Comment by rfc2822** [comment]
@shiba89 I don't understand the argument. You may also have changed the password on your private server.

But yes, logs and steps to reproduce would be helpful if you think this is a problem of DAVdroid.

**Comment by gedakc** [comment]
@shiba89, do you have a self-signed certificate using an IP address only?  If so then you might try 0.6.10.1.  See also issue #410 [1]

[1] https://github.com/bitfireAT/davdroid/issues/410

**Comment by shiba89** [comment]
I found the reason why this happens watching the logs with adb. It seems that owncloud appends @server.hostname.com to every vCard UID field. Since I have had this contact list for several years, some vCard had the hostname of my previous server.

Davdroid <0.6.10 apparently ignores this field, so that's why I never noticed the problem until now. However since 0.6.10 it tries to sync a modified contact to the server pointed by its UID. Removing every UID solved the problem.
