### ISSUE TITLE
Translate do Português BR

### ISSUE THREAD

**Issue by FabianoK** [bitfireAT/davdroid#417]
I would translate the application to Portugês of Brazil and like send the xml file to aggregate in application. How to proceed? I translate the aplication to Portugês of Brazil and like send the xml file to agregate in application. How do proced

**Comment by devvv4ever** [comment]
Hello! Thanks, that'd be great. You need to fork the project and edit the strings.xml with the translations. Please send a merge request after that and we will merge it to master.

**Comment by rfc2822** [comment]
Thanks for the offer! You can find the strings in the https://github.com/bitfireAT/davdroid/blob/master/app/src/main/res/values/strings.xml file. You can do a pull request or just send the translated strings to play@bitfire.at.

**Comment by rfc2822** [comment]
Done with 81eabf5961cfde5aa02fc4aeb0270549bf1656fa, thanks.
