### ISSUE TITLE
UI problems when URL contains space character during account setup

### ISSUE THREAD

**Issue by untitaker** [bitfireAT/davdroid#419]
When entering an invalid URL during account setup, the "next"-button does nothing.

**Comment by rfc2822** [comment]
Where is the problem? It should be grayed out.

**Comment by untitaker** [comment]
I see now that it's grayed out, but this is hardly visible (only when tapping on it) and is not good UX IMO.

**Comment by rfc2822** [comment]
What do you suggest? It's disabled so that users can't continue. How this is rendered depends on your theme (in my case, I use a theme where I can clearly see what is disabled). Maybe a hint "invalid URL" could be displayed below the URL when it's invalid, but this would also appear when the user has entered a partial URL and has not finished yet, which I think would be confusing.

**Comment by untitaker** [comment]
A toast message when trying to tap the button would be nice.

**Comment by rfc2822** [comment]
But that would imply that one could press the button, i.e. start the next action, with an invalid URL.

Have you been confused by the current behaviour? In which way?

**Comment by untitaker** [comment]
>But that would imply that one could press the button

With the default theme, this implication is already there because there is no visual difference (to me) between a tappable and disabled button.

**Comment by rfc2822** [comment]
> With the default theme, this implication is already there because there is no visual difference (to me) between a tappable and disabled button.

So I'd say this is the real problem. We have used default Android icons, but maybe there would be better ones…

**Comment by untitaker** [comment]
But even if you used a better icon, the user still would have no idea what exactly is wrong.

**Comment by rfc2822** [comment]
There's the message "Please enter an URL", and some garbage with a space isn't an URL :p

**Comment by untitaker** [comment]
I don't see such a message. As said, the button does absolutely nothing. This is on CM11

**Comment by rfc2822** [comment]
Ok, the message is "Base URL (…):" but it still says "URL".

I won't change the concept of the disabled Next buttons as it's a common Android pattern (see the Email account setup). The only possible thing would be to add a hint for invalid or incomplete URLs, but I'd prefer to trust users to know that URLs must not contain space characters. After all, they must have got their CalDAV URL from somewhere and this source mustn't show a space in the URL.

**Comment by untitaker** [comment]
>Ok, the message is "Base URL (…):" but it still says "URL".

Oh you meant the normal label, then nevermind.

I probably overestimated this issue because I entered my server URL by hand.

**Comment by rfc2822** [comment]
> I probably overestimated this issue because I entered my server URL by hand.

Do you have spaces in your URLs? Where did you get it from?

**Comment by untitaker** [comment]
It was a typo, unlikely to happen though. I think I tapped `` `` when I was trying to hit ``.`` or so.

**Comment by rfc2822** [comment]
Ah ok. I guess I'll close this with your permission... if someone digs it out some time, we can think about it again ;)

**Comment by untitaker** [comment]
Sure.
