### ISSUE TITLE
Xperia Z3 Contact Name Issue 

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitfireAT/davdroid#422]
Hi,
actually I encountered a problem using DAVdroid to sync my Contacts with ownCloud.
Though Firstname and Surname is filled and indicated correctly on my Z3, as well as using the Web client of ownCloud, the Contact Name is schown as 'Firstname Surname Surname Firstname' within the Z3 Contact App.
Selecting a different Name to be shown of an other Account (eg. Skype or Threema) leads to a correct indication.
So the problem occours only if there is NO other Contact Entry then the one imported by DAVdroid from ownCloud.
Changing the composed name field is not possible (Changes are accepted but not saved).
Changing the surname or firstname field is possible and leads to a changed name.
Guess there is a problem in building the composed display name of a contact.
I've no idea if DAVdroid or the Contact APP causes that problem.
Any Idea what is going wrong here?

Best
Stephan

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including detailled steps to reproduce the issue and [verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs).

**Comment by rfc2822** [comment]
Any news on this?
