### ISSUE TITLE
Can't sync Google Contacts

### ISSUE THREAD

**Issue by SpyMachine** [bitfireAT/davdroid#423]
I've been able to sync my Google Calendar with the url: https://wwww.google.com/calendar/dav. What url can I use to sync my Contacts? All the ones that I have found on Google support have not worked.

**Comment by untitaker** [comment]
In which way did they not work? Also, see http://evertpot.com/google-carddav-issues/ for many possible explanations.

**Comment by SpyMachine** [comment]
They just show up with no Address Books. I'm thinking it's cause I need the correct URL for CardDav and I just haven't found it yet.

**Comment by phy25** [comment]
You may be interested to see #122. Since Google's port is not standard at all, the author will not add support to it.

**Comment by rfc2822** [comment]
Please follow up in #234.
