### ISSUE TITLE
'Unable to resolve host'

### ISSUE THREAD

**Issue by gour** [bitfireAT/davdroid#425]
Hello,

at the moment I run ownCloud-7 on my own desktop machine and try to sync phone data using latest Davdroid, but I receive:
```java.net.UnknownHostExcepton:
Unable to resolve host "myhost.net": No address associated with hostname at 
java.net.InetAddress.lookupHostByName(InetAddress.java:439)...
```

Considering that 'myhost.net' is dyndns domain provided by No-IP, I wonder if DAVdroid is meant to work in such environment?

Let me say that the above is via http protocl - I've tried with self-signed SSL certificate, but could not make it work always getting SSL protocol error, so I tried with http.

My plan was/is to possibly buy No-IP's Plus DNS service to be able to use custom domain and StartSSL certificate, but wonder whether DAVdroid requires that one has reverse DNS set for the domain as well in which case I'd consider to use some ownCloud provider or put it under VPS?

**Comment by untitaker** [comment]
Can you access ownCloud from your phone's browser?

**Comment by gour** [comment]
> Tunnel session failed: ngrok2 does not allow anonymous tunnels yet

Hmm...at the moment I see that the browser is showing login screen, but not being able to connect. :-/

However, ownCloud file client does work...will investigate further...

**Comment by gour** [comment]
I did install OC on my Linode VPS and today got same error, although it does not happen all the time.

Morever, my Android browser has problem logging in...I'm waiting to create StartSSL certificate in order to test with https.

**Comment by reox** [comment]
Hi,
i got the same issue since the last update of davdroid (Now on GP Version 0.6.10.1). I can not reproduce it but i think it happens when my phone enters a WLAN and loses its mobile connection.
It happend so far only at work where the accesspoint is quite far away and probably has an unstable connection.
Server is Radicale on static IP with CA signed certificate.
Phone Nexus 5 / Android 5.0.1
I tried to recover the message from adb logcat but it seems it got already deleted :(

**Comment by rfc2822** [comment]
Is it possible that these issues happened earlier but you just didn't notice them because there was no notifcication?

**Comment by reox** [comment]
if you added the notification in 0.6.10.1 thats probably the case. For me it does not seem uncommon that the phone loses its internet connection while syncing.

**Comment by rfc2822** [comment]
> if you added the notification in 0.6.10.1 thats probably the case. For me it does not seem uncommon that the phone loses its internet connection while syncing.

Indeed, and as far as I remember, the notification shouldn't pop up for (soft) I/O errors, but apparently it does. Probably yet another bug…
