### ISSUE TITLE
Davdroid don't syncronise anniversary

### ISSUE THREAD

**Issue by tioannidis** [bitfireAT/davdroid#426]
Hello,
I use Davdroid 0.6.10.1 on Android 4.4.4 PACMANROM(KK RC-3 dev). The Mobilephone is a Samsung GT-I9000.
The issue is, I can't syncronise(posteo.de) the anniversary into my contacts, only the birthdays. This information will be not transferred to the server.   

Best regards,
Theo

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including detailled steps to reproduce the issue and [verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs).

**Comment by tioannidis** [comment]
here is the description how to reproduce the issue:

for the first I've created a new contact with a birthday and an anniversary(Jahrestag:6.Sep.2006) like this:

![contact1](https://cloud.githubusercontent.com/assets/1592909/5696160/d87f411e-99c3-11e4-8acf-df343c51e42b.jpg)

after the Davdroid-syncronisation with posteo.de, the contact is saved without the anniversary:

![contakt2](https://cloud.githubusercontent.com/assets/1592909/5696198/7b5ba57a-99c5-11e4-9985-9037dcd246bb.jpg)

This sreenshoot is from the Posteo.de Webinterface. The anniversary was not syncronised, only the birthday.

sorry, but i have not the possibility to get the verbose logs. can somebody else try to reproduce the issue and post the logs?

**Comment by vacy** [comment]
Hi guys,

I've this issue with owncloud 7.0.4 too.
I got the logs by davdroid 0.6.10.1, here is an excerpt:
W/davdroid.Contact( 4216): Created potentially invalid VCard! [Anniversary] | W02: Property is not supported in this vCard version.  Supported versions are: [4.0]

Here is the complete, anonymized log: https://gist.github.com/e78acfe35bfea712f4be.git
Phone: OnePlus One, Cyanogenmod 11 M11 - Android 4.4.4

Cheers,
Florian

**Comment by rfc2822** [comment]
@vacy The logs are empty.

**Comment by vacy** [comment]
@rfc2822 oooh sorry, here they're: https://gist.github.com/vacy/f2baf5be0f33ffd4f47f

**Comment by rfc2822** [comment]
CardDAV uses VCard 3 by default, i.e. CardDAV clients and servers MUST understand VCard/3. VCard/3 defines BDAY (birthday) but not ANNIVERSARY.

DAVdroid doesn't support VCard/4 (yet). VCard/4 defines ANNIVERSARY.

So, there are multiple ways to implement ANNIVERSARY with VCard/3:

1. use ANNIVERSARY even if it's not defined (the way used by DAVdroid), because unknown properties must be ignored by clients/servers – this is ,
2. use X-ANNIVERSARY – this is used by posteo,
3. use other field names – this is used by iCloud, they seem to name the fields "itemN.X-ABDATE".

Conclusion: Currently, it's not possible to sync ANNIVERSARY reliable with DAVdroid because with VCard/3, there are different methods to implement ANNIVERSARY and DAVdroid can only use one of them.

**Comment by untitaker** [comment]
>unknown properties must be ignored by clients/servers

Simply... ignored? This sounds like a good way to loose data, even if it's mandated by the standard.

**Comment by rfc2822** [comment]
> Ignored or removed? Latter sounds like a good way to loose data, even if it's mandated by the standard.

DAVdroid doesn't remove the X-ANNIVERSARY (if used by the server) or other properties (see #118). They just won't get parsed. If you add an anniversary with DAVdroid, there will be even two properties: an ANNIVERSARY (used by DAVdroid) and an X-ANNIVERSARY (used by the server). Of course, the different ANNIVERSARY properties are not in sync in this case.

**Comment by jkufner** [comment]
Unknown properties must be both ignored and preserved. I'm not sure
about exact formulation in the standard, but all clients I've seen do
that. They simply store unknown properties without understanding them
and change only what they know.

**Comment by rfc2822** [comment]
> Unknown properties must be both ignored and preserved.

And that's what DAVdroid does. Where do you actually see a problem? Please provide examples.

**Comment by jkufner** [comment]
rfc2822 wrote, on 18.1.2015 20:02:
> And that's what DAVdroid does. Where do you actually see a problem?
> Please provide examples.

That was reply to message from Markus about loosing data.
