### ISSUE TITLE
Please add option to disable notifications introduced in 0.6.10

### ISSUE THREAD

**Issue by Whoopie** [bitfireAT/davdroid#428]
davdroid 0.6.10 added support to show notifications on sync errors (Android 4.1+).

My sogo server is only available in my LAN, so I get sync errors as soon as I leave my home.

It would be great if you added an option to disable these notifications. Thanks in advance!

**Comment by rfc2822** [comment]
There's already an option for that: http://www.droid-life.com/2012/11/29/how-to-disable-android-application-notifications-beginners-guide/

**Comment by Whoopie** [comment]
Thanks!
