### ISSUE TITLE
Cannot add calendar to sync

### ISSUE THREAD

**Issue by Yajo** [bitfireAT/davdroid#432]
Today, I added a new calendar to my OwnCloud server and noticed that there's no [obvious] way to add a new calendar to sync in the same account. I had to delete the account and configure it again, which does not seem very user-friendly.

**Comment by devvv4ever** [comment]
Yes, we know. "Account settings" is a priority goal on our agenda.

**Comment by rfc2822** [comment]
Thanks for your report. Please follow up in #219.

PS: High-quality pull requests are always welcome.
