### ISSUE TITLE
Manually set per-account sync interval

### ISSUE THREAD

**Issue by DemoFreak** [bitfireAT/davdroid#440]
Hi, and thanks for this useful software.

It'd be nice to have an option to set a sync interval, or maybe to trigger sync after every completed edit.

**Comment by rfc2822** [comment]
> It'd be nice to have an option to set a sync interval, or maybe to trigger sync after every completed edit.

What do you mean - edit on Android or server side?

**Comment by DemoFreak** [comment]
On Android. Edit on Android -> (nearly) instant sync.

Edits on server side could only be detected by polling, if I understand correctly. Thus far I hit the "Sync now" menu entry after some time period (when I lose patient ;-) and it'd be nice if there were an option like "Sync/poll every x minutes".

**Comment by rfc2822** [comment]
> On Android. Edit on Android -> (nearly) instant sync.

This is already done by Android, unless you disable Sync (for instance, by limiting syncs on mobile connections in the settings or energy-saving mode). Changes on your devices will be synced "immediately" = about 1 min after editing. It they are not, you have activated some kind of limit.

> Edits on server side could only be detected by polling, if I understand correctly.

Indeed, or by keeping a always-on connection to the server (I think that's how Apple has implemented iCloud sync to their OSX clients), but that's not within the scope of DAVdroid.

>Thus far I hit the "Sync now" menu entry after some time period (when I lose patient ;-) and it'd be nice if there were an option like "Sync/poll every x minutes".

For calendars, there's a Refresh menu entry in the Calendar app that does exactly that by 1 click.

For address books, there's no such thing in the default address book app, so it's at the moment the only reason why you might sync using the Settings.

Please see also https://davdroid.bitfire.at/configuration#c123

**Comment by rfc2822** [comment]
Done with 933f99b563df012a07b48cbaa1aaa88f123189d9 (0.7).
