### ISSUE TITLE
Can't connect to Baikal

### ISSUE THREAD

**Issue by XenGi** [bitfireAT/davdroid#442]
# Server config:

  - Baikal 0.2.7
  - Nginx 1.6.2
  - PHP-FPM 5.6.5
  - Archlinux

Baikal is configured with a subdomain `baikal.myserver.com` and Basic Auth to support preemptive authentication.

# Client config:

  - Oneplus One
  - Cyanogenmod 11S (Android 4.4.4)
  - Davdroid 0.6.11 from F-Droid

Settings i put in Davdroid are:
  - Base URL: `https://` `baikal.myserver.com`
  - Username: `MyUser`
  - Password: `MyPassword`
  - Preemptive authentication: `Yes`

The Error Message I get is:

```
Missing capabilities: Invalid DAV response:
207 Multi-status expected but not received
```

My nginx error log is empty. In the access log I see this:

```
88.73.93.95 - MyUser [13/Feb/2015:17:37:06 +0100] "PROPFIND /.well-known/carddav HTTP/1.1" 302 154 "-" "DAVdroid/0.6.11" "-"
88.73.93.95 - MyUser [13/Feb/2015:17:37:06 +0100] "PROPFIND /card.php HTTP/1.1" 207 402 "-" "DAVdroid/0.6.11" "-"
88.73.93.95 - MyUser [13/Feb/2015:17:37:06 +0100] "PROPFIND /card.php/principals/MyUser/ HTTP/1.1" 200 353 "-" "DAVdroid/0.6.11" "-"
```

**Comment by devvv4ever** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

**Comment by XenGi** [comment]
The error seems to be on the Baikal side.
I have a quite complex setup. My Baikal runs inside an LXC on the server and the SSL termination is handled outside. This seems to cause trouble in Baikal.
I tried everything directly without  LXC and it works. So theres so issue on the DAVDroid side.

**Comment by XenGi** [comment]
Was my fold. wrong configuration in baikal. Just used the nginx config which is provided with baikal and it works now.

**Comment by devvv4ever** [comment]
Thanks for the update! Great that you found the problem and that all is working as expected!
