### ISSUE TITLE
NotFoundException: 404 Not Found

### ISSUE THREAD

**Issue by wurstchristoph** [bitfireAT/davdroid#443]
# error

I get sync errors on my Nexus 7:

    at.bitfire.davdroid.webdav.NotFoundException: 404 Not Found
    at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:415)
    at at.bitfire.davdroid.webdav.WebDavResoruce.checkResponse(WebDavResource.java:393)
    at at.bitfire.davdroid.webdav.WebDavResource.multiGet(WebDavResource.java:331)

Is far as I could check, calendar events seem to be synced (at least server to client) correclty.

On my phone (Nexus 4, CM11 ~ Android 4.4.4), however, everything syncs without any issues.

# my setup
- Nexus 7 (Stock Android 5.0.2)
- davDroid 0.6.12 (from F-Droid)
- ownCloud 8.0 stable (SSL)

# owncloud.log
    {"reqId":"a35f71c4db38d93424c6e999744a5159","remoteAddr":"X.X.X.X","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-02-15T20:11:16+00:00"}

# screenshot
![nexus7_davdroid_bug](https://cloud.githubusercontent.com/assets/1374172/6204822/4561aeb6-b558-11e4-8b32-b53101c347c9.png)

**Comment by rfc2822** [comment]
Please provide steps to reproduce and logs.

Is there any indication that this is a client issue? 404 Not Found sounds like a server issue to me.

**Comment by rfc2822** [comment]
Is this a duplicate of #411 ?

**Comment by wurstchristoph** [comment]
You are right, this seems to be a server issue since other clients (e.g. Evolution/Linux) cause this server side exception too. I reported the issue at the ownCloud/Calendar repo https://github.com/owncloud/calendar/issues/734

**Comment by georgehrke** [comment]
> 404 Not Found sounds like a server issue to me.

Nevertheless the client must not crash and should handle http response codes correctly (e.g. ignoring this event)

**Comment by rfc2822** [comment]
> Nevertheless the client must not crash and should handle http response codes correctly (e.g. ignoring this event)

It doesn't "crash" and notifying the user of errors is good practice. You may disable the notifications.

404 is a hard error and should not be ignored.

**Comment by georgehrke** [comment]
but in @wurstchristoph's bug report it sounds like the whole calendar stops syncing, just because one object returns a 404. That should not be the expected behaviour.

**Comment by georgehrke** [comment]
The app should definitely show some kind of notice to the user, but it must not stop syncing the other events.
