### ISSUE TITLE
integrate davdroid as a library/module and use already existing account

### ISSUE THREAD

**Issue by mahermeg17** [bitfireAT/davdroid#446]
Hi, 
I just integrated davdroid as a module into my own application whitch already create an account for the user. davdroid is now accessible from a menu in my app. I want to hide all possibilities for the user to setup his account, just to confirm which account as the some type account as my app, and use in background the already existing account.
To start, I made some modif in showSyncSettings into the MainActivity:
public void showSyncSettings(Context context, MenuItem item) {
		Intent intent = new Intent(Settings.ACTION_SYNC_SETTINGS);
        intent.putExtra(Settings.EXTRA_ACCOUNT_TYPES, MY_ACCOUNT_TYPE);
		context.startActivity(intent);
	}

but this have no effect, all the sync account like gmail, linkedin are shown.

help please!

**Comment by rfc2822** [comment]
This is not a DAVdroid issue. Feel free to use DAVdroid in terms of the GPLv3 license, but please understand that I can't provide instructions on how to brand/integrate it here.
