### ISSUE TITLE
Error synchronizing CalDAV with Open-Xchange (ical4j, strict problem?)

### ISSUE THREAD

**Issue by pdf** [bitfireAT/davdroid#452]
Events created server-side, via Thunderbird or web UI work fine, and are populated on Android via DAVdroid as expected, however events created on Android are not successfully sync'd to Open-Xchange.

Last few frames of the Open-Xchange stack trace, plus DAVdroid logcat output are available here:

https://gist.github.com/pdf/006b785248dec5e43cdf

I can't find any way to configure Open-Xchange to use relaxed parsing, perhaps this is a build-time option, however if Thunderbird can successfully create events it seems like DAVdroid should be able to as well.

**Comment by rfc2822** [comment]
> I can't find any way to configure Open-Xchange to use relaxed parsing, perhaps this is a build-time option, however if Thunderbird can successfully create events it seems like DAVdroid should be able to as well.

AFAIK, mailbox.org uses Open-Xchange and it works there.

Can you please provide further information on whether DAVdroid generates invalid dates/iCal files or whether this is a server issue?

**Comment by pdf** [comment]
How do I provide that information?  As I said, Thunderbird works fine with the same server...

**Comment by rfc2822** [comment]
It seems to be about this line:

```
D/Wire    ( 5048): http-outgoing-0 >> "DTSTART;TZID=Australia/Lord_Howe:20150321T193000[\r][\n]"
```

which is in the context of the Australia/Lord_Howe time zone. Can you please try to add an event in another time zone?

**Comment by pdf** [comment]
Yep, that works.  Any idea why that might be a problem?  I generally use the telco operator's provided timezone for travel, and that's the zone they apparently choose here (though I have no idea why, there's a standard timezone that should cover this region).

**Comment by rfc2822** [comment]
> Yep, that works.  Any idea why that might be a problem?

The timezone definitions are from the Olson DB which is shipped with ical4j. I guess that the Australia/Lord_Howe timezone in ical4j is somehow corrupt.

Could you please create an issue at https://github.com/ical4j/ical4j/issues and link it with this issue?

**Comment by pdf** [comment]
Done, thanks a lot for the timely and helpful reponse.

**Comment by rfc2822** [comment]
If this issue affects you, please follow up at https://github.com/ical4j/ical4j/issues/28.
