### ISSUE TITLE
Option to add new calendar to account

### ISSUE THREAD

**Issue by ovidiub13** [bitfireAT/davdroid#453]
When I created the account, I had 3 calendars, in my kolab server. Since then I've created several new calendars. How do I add new calendars to my account?

**Comment by devvv4ever** [comment]
Currently you either need to create an additional account adding only this resource or delete the one you have and add one account with all resources. We know this isn't the optimal workflow and we're already planning a release with the the first steps of a settings dialog. It should come in the not too distant future ;)

**Comment by devvv4ever** [comment]
Since this is a duplicate, please follow up in #154
