### ISSUE TITLE
carddav not syncing contact groups

### ISSUE THREAD

**Issue by ka223** [bitfireAT/davdroid#454]
Carddav is not syncing contact groups.

DAVdroid 0.6.12
Server Owncloud 8

Group sync works with Sogo Connector+Thunderbird, so it seems to be a davdroid problem.

**Comment by devvv4ever** [comment]
Thanks for the report. Does Owncloud 8 work in general? Are you maybe affected by a recently often reported problem caused by Owncloud 8: https://github.com/owncloud/core/issues/14048

Can you verify that everything else works except groups? Do you know if group handling has changed in the new version of owncloud compared to oc7?

**Comment by ka223** [comment]
Contact and calendar syncronisation works in both directions, exept the contact groups.

It is a fresh owncloud 8 install, I never used owncloud 7.

**Comment by devvv4ever** [comment]
Do you mean contacts which are not inside a group are synced correctly?

**Comment by devvv4ever** [comment]
To investigate further please send us verbose logs from your phone. We've written a tutorial on it here: https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by ka223** [comment]
I tested some time and I can not create a carddav phone book entry with a group on my phone.
android 4.1, contacts version 4.1.1-100

First time I created an empthy phone book and copied my contacts to the davdroid list. 
Groups are not sync to owncloud, even if I create the contacts on owncloud.
Now, I created a test contact list, test entries are syncronized from owncloud to the phone with groups. But if I change the contact name at owncloud, it is not changed at my phone. It is synced, I can see the changed name at the contact settings ...

Maybe I can provide some logs later, but every contact, even the pictures are in these logs.

**Comment by ka223** [comment]
Tried with an android 4.4 VM, the groups can not be managed at android or syncronized from android to owncloud and contact names are not updated at the contact list.
Screen Capture: https://copy.com/KtG4wnnUgnGKYSdw

**Comment by go2null** [comment]
See #48

**Comment by rfc2822** [comment]
Please follow up in #48.
