### ISSUE TITLE
Davdroid task support

### ISSUE THREAD

**Issue by accuraz** [bitfireAT/davdroid#455]
Is Davdroid actually supporting tasks within calendars ?

I use Davdroid with a Baikal server. I tested a couple of Android calendars witch are supporting tasks management but I get only locale tasks support despite the fact that every Android calendars softwares I tested are supporting caldav tasks.

So I'm wondering if it's a Davdroid related issue.

Does someone have informations about that ?

Thank you par advance.

**Comment by rfc2822** [comment]
Please follow up in #34.
