### ISSUE TITLE
Option in FAQ's to set synchronization interval does not exist?

### ISSUE THREAD

**Issue by tombrossman** [bitfireAT/davdroid#458]
The FAQs have a [page describing the process for adjusting sync interval](https://davdroid.bitfire.at/faq/entry/how-to-change-sync-intervals) from the default of one day. When I try to do this, the option does not exist - I see only cancel or remove account. Everything else works perfectly but I'd love to get sync working every 30 minutes or so.

![2015-03-09 08 39 59](https://cloud.githubusercontent.com/assets/6167915/6552061/4187a132-c639-11e4-9d68-42bcf3334b6b.png)

**Comment by devvv4ever** [comment]
Settings have been introduced in DAVdroid 0.7. They are accessed either from the "DAVdroid Accounts" overview - (**not** inside a certain account, Android requires a seperate section for Account settings!) or via the app start screen.
