### ISSUE TITLE
Only Read-only access to fastmail carddav

### ISSUE THREAD

**Issue by shanghaiknight** [bitfireAT/davdroid#468]
When using fastmail carddav, with davdroid, i only get read-only access to the contact address book.  i have to log into fastmail carddav using the "url" option.  It shows my default address book, but it shows it will be read only access.

I have a tablet using aosp android 5, and a stock Samsung s4, running 4.4.4. The situation is the same on both devices.

In using davdroid .7.1

**Comment by rfc2822** [comment]
> When using fastmail carddav, with davdroid, i only get read-only access to the contact address book.

What does that mean? Android doesn't know read-only contacts.

Please give steps to reproduce so that we can understand the problem.

Is this a feature request for supporting read-only address books (= contacts)? Is this issue related to #434?

**Comment by shanghaiknight** [comment]
Not related to the feature request.  I've attached a screenshot.  When adding the Fastmail Account, the addressbook is only available as Read-Only.

Steps to reproduce
1. Select icon to add Account.
2. Select URL method
3. Use carddav.messagingengine.com
Username:   xxxxxxx@fastmailbox.net   (My Fastmail Domain login)
Password:  XXXXXXXXXXXXX

The following is the resulting screen:
![screenshot_2015-03-16-10-56-54](https://cloud.githubusercontent.com/assets/11495598/6668799/a054971e-cbcb-11e4-9b68-f7a1e203c53a.png)

**Comment by shanghaiknight** [comment]
This is not related to the feature request.

When I add the fastmail account, DavDroid informs me that it can only add the carddav account as read-only.  Using another CardDav sync app with the same credentials does not yield the same results.

Steps to reproduce
1. Open DavDroid
2. Select new account button
3. Select "URL" method
4. Type carddav.messagingengine.com
Type username   xxxxxxxxx@fastmailbox.net (my fastmail login domain)
Type password  xxxxxxxxx - strong password with lots of symbols

The result is the following screen indicating that the address book is 'read only'...

![screenshot_2015-03-16-10-56-54](https://cloud.githubusercontent.com/assets/11495598/6668873/2d137e5e-cbcc-11e4-9330-9fa0b7a28cf3.png)

**Comment by rfc2822** [comment]
And is it read-only? The icon is normally shown only when the server says that the collection is read-only.

Also, for address books, the read-only icon in DAVdroid doesn't mean anything. Do you experience problems? Can you add a contact to this address book in DAVdroid and sync successfully?

**Comment by shanghaiknight** [comment]
I completed the account creation process. It doesn't seem to have sync'd anything.  No contacts are displayed, other than the one I created for a test.

All works fine with CardDav on my other device, same settings.  It must not be connecting correctly to the server.

**Comment by rfc2822** [comment]
Is this still an issue? I'm asking because you have closed the issue.

Also, I can't reproduce the issue here: FastMail address book is working here and not displayed as read-only.

Which FastMail product do you use? Is it possible that the address book is really read-only? Did you try with other clients?

**Comment by shanghaiknight** [comment]
Didn ot mean to close it, must have hit the wrong button.  

Well, everything eventually sync'd over, both ways, despite the warning that it would only be read only.  So it is working, but the read only warning needs to be changed.  I'm fine with this staying closed.

**Comment by rfc2822** [comment]
Ok, if something doesn't work, just post here again.
