### ISSUE TITLE
How to rename calendar locally?

### ISSUE THREAD

**Issue by gn36** [bitfireAT/davdroid#474]
It should be possible to Rename DAVdroid calendars. I am using quite a few calendars and unfortunately, the name of many of them is just "Calendar MyName". Since I can't change that when adding the calendar to my system, I now have a lot of calendars named "Calendar MyName" in my calendar app, which all synchronize perfectly, but are hard to keep apart. By temporarily changing my name in the system they synchronize with I can change the name that will be shown, but I don't have access to this setting on all machines (since obviously, my name usually doesn't change often).

Obviously, the different calendars still have different colors, but it would be easier to differenciate if I could rename the calendar before adding it to my system. In the synchronization settings, it is much easier to differenciate, because I can use a custom name there. But that one is not shown in the calendar app itself.

**Comment by rfc2822** [comment]
> it would be easier to differenciate if I could rename the calendar before adding it to my system

DAVdroid takes the name from the CalDAV server. Can you name your calendars on your CalDAV server?

**Comment by gn36** [comment]
No, unfortunately I have no access to these settings. They are, by default named as "Kalender FirstName SecondName"

**Comment by rfc2822** [comment]
I don't know whether it's in the scope of DAVdroid of renaming calendars. The server should provide the correct name. Would it be possible for you to get access to these settings? Which server are you using?

In the meanwhile, there might already be another app that could be able to help you, as renaming the (local Android) calendar could be done by any calendar app and is not restricted to DAVdroid.

**Comment by gn36** [comment]
The server side software is Egroupware on multiple servers. But from it's perspective the name is ok since it is delivering my calendar - except that it is not the only one doing so.

Are you talking about any specific calendar app which can rename those calendars? Obviously that would be fine too, but so far I haven't come across one. From the perspective of the calendar app, the calendar is provided by DAV-droid.

**Comment by rfc2822** [comment]
At the moment, renaming calendars locally is not within the scope of DAVdroid. However, you may follow up in #154 because renaming would be an operation in the "view/change DAVdroid account" GUI.

I don't know if there's really an app for it, but it shouldn't be too difficult to just change the [CALENDAR_DISPLAY_NAME](http://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns.html#CALENDAR_DISPLAY_NAME). There should be no side effects.

If you have root access, you may even use SQlite to change the name in the database (`/data/data/com.android.providers.calendar/databases/calendar.db`, table `calendars`) yourself.

**Comment by gn36** [comment]
Ok #154 is much more sophisticated than this request. 

For me it would have been enough to make the name that was imported from the server editable when it is first displayed when setting up the connection. I am not a Java Developer, but I would think this is not much more than changing a label to a textbox and writing the content of the textbox instead of the string comming from the server to the database.

**Comment by rfc2822** [comment]
> I am not a Java Developer, but I would think this is not much more than changing a label to a textbox and writing the content of the textbox instead of the string comming from the server to the database.

According to my experience, even the craziest CalDAV/XML/HTTP problems are _nothing_ compared to GUI tasks like creating a text field (and: making it actually editable, the cursor not disappear, scrollable, not crashing when the screen is being rotated and or a TV is attached; it should also retain the contents when the users switches to another activity and then back; and of course it must work on 24" TV screen as well as on wearables………). OK, maybe somehow over-exaggerated, but I want to say that even a simple GUI change is lot of work and may cause lots of trouble.

But the main reason for not implementing this is that the server already provides a "display name" for the calendar. If you want to change the displayed name of the calendar (= display name), you have to make the server providing the correct display name.

> No, unfortunately I have no access to these settings.

Who has access to these settings? Would your administrator be able to rename the calendars?

**Comment by gn36** [comment]
Ah I guess I underestimated the work for guis. 

No, I have full access to one of the servers and the only thing I can change is the users Name which will then be reflected in the Name Tag sent to Dav droid. I found no settings to control the naming by itself. If I change the name, nobody will know who created a an event or who participates. Only the admin can set the name. Right now I changed my name on the system I can access and changed back after the account was created, but that isn't a solution you can talk an admin into.

**Comment by evert** [comment]
Sounds like an inferior dav server then. Most allow control of the `{DAV:}displayname` property without interfering with anything else.

**Comment by rfc2822** [comment]
So, renaming calendars locally is not supported.
