### ISSUE TITLE
Don't sync until Android says it has internet connectivity

### ISSUE THREAD

**Issue by arty-name** [bitfireAT/davdroid#480]
I connected to a hotel wifi which requires signing-in on a separate html page, a common thing. I saw two notifications popping up: Android's "This wifi requires signing in" and DavDroid's "SSL connection error". I assume Android has some API that tell you when current network gets real internet connectivity. Would be nice if DavDroid only tried to sync after that moment.

**Comment by rfc2822** [comment]
Hello, thanks for the suggestion. But how should DAVdroid detect whether there is "real" Internet connectivity? Also, the sync process is not initiated by DAVdroid but by Android.

**Comment by arty-name** [comment]
Well, I don't really know Android APIs. I know that the notification area wifi icon is grey when there's a wifi connection and blue when there's actual internet connectivity. I assumed there's some API to tell us this state. However if it's Android who initiates the sync and it does that in the wrong moment probably there's nothing you could do.

**Comment by rfc2822** [comment]
I guess your suggestion would be a good idea, but as the sync is triggered by Android, I don't see any chance, so I'll close this for now.
