### ISSUE TITLE
Crash after installation compiled with eclipse luna

### ISSUE THREAD

**Issue by nedimhx** [bitfireAT/davdroid#481]
After I import project to eclipse and add lombook.jar.
I have sucessfull build app without any errors or warnings, but when I install it, and try to open, it just crash, without any error message.

App is tested on Galaxy Note 4 Lollipop 5.0.1

Screenshout:
http://prntscr.com/6uh4bk

**Comment by rfc2822** [comment]
The screenshot shows only a white screen, is this correct? I don't see the point. Do you have experience with Android apps/Eclipse? Currently, Android Studio is recommended to build DAVdroid. Did you do it as described in https://github.com/bitfireAT/davdroid/wiki/Compiling ?

**Comment by nedimhx** [comment]
In the printscreen I want just to show it that there is not any errors.

I'm working on couple apps, and only work with eclipse.
I have download android studio, import project and generate .apk file. 
But can you help me to change package name, any method I have find on google and use it, error was be while instalation
