### ISSUE TITLE
"Couldn't parse Multi-Status response on REPORT multi-get" in signed version

### ISSUE THREAD

**Issue by nedimhx** [bitfireAT/davdroid#485]
This error ocure only when I upload app to google play store. But when I debug it in Android studio, and test in emulator and on my Note 4 everything is fine.

But like I said, after I upload it to google play store, and download it once it is available. After input username and password of owncloud server and want to syncs contacts or calendar after I click on next, a got that error.

What is wrong ?

**Comment by nedimhx** [comment]
Also what I have noticed, as I cant use davdroid what I am uploaded to google play store, I have exported another one with diferent package name, to use until fix that one from play store.
But ever time when I add card dav account and on last step where I set name for that account, on finish button app is crash.

When I uninstall app from play store, secon one i working fine

**Comment by dper** [comment]
Why would you upload and then download from the Play Store? That sounds like a waste of time when you could just install the app already.

**Comment by nedimhx** [comment]
I can install it allready, for testing purpose, and everything is fine. But when users download it from play store, they get that error. Thats first time when I notice that error. User has send report.

Then I uninstall my app which I installed from local apk and install new from play store and get same error.

**Comment by nedimhx** [comment]
I have build fresh code from github, just change package name, and when I test it localy with apk instalation, everything is fine, but when I upload it to google play store and install from that location. I get same error.

Does anybody know what is probl ?
@devvv4ever @dper @rfc2822

**Comment by nedimhx** [comment]
I have discovered something new.

When I export signed app from Android studio and test it locali, everything is ok.
But if I zipalign that apk file, and then install it localy, app behaves same as when I install from google play. 

Can it be some problem with zipalign ?

**Comment by nedimhx** [comment]
******UPDATE******

It's not problem with zipalign, its with SIGNING AN APP
I have try with signed app and with unsigned, with out zipaliging both of them. Forget zipalign !
First try with signed and error ocure, after uninstalling and then install UNSIGNED app everything was be fine.

So what problem can be with signing app?

**Comment by nedimhx** [comment]
****UPDATE 2****

Debuged signed app is working fine, so only problem is with relased signed app.

**Comment by rfc2822** [comment]
1) As far as I can see, this is not a DAVdroid issue. Did you ask the question on StackOverflow? Maybe we can continue there.

2) Maybe the problem is related to ProGuard and/or DRM? Class and method names must not be mangled because the libraries DAVdroid use rely on reflection heavily.

**Comment by nedimhx** [comment]
I have download fresh files from github, import lombook library and build app, signed relase app gets same error, signed debug app work fine.

Then on fresh VPS install owncloud and everything what is needed for owncloud, try apps. Signed relase app again gets sam error, signed debug app work again fine.

I have ask on stuackoverflow, 12 views, 0 answers
http://stackoverflow.com/questions/29878220/missing-capabilities-invalid-dav-response-couldnt-parse-multi-status-response

If you want, I can provide you fresh installed CentOS 6.5 VPS and you can try ?

**Comment by rfc2822** [comment]
Sorry, I can't help you in that. Building works for other people, including F-Droid. You may download the Fdroid server to reproduce building the (working) APK that F-droid uses.

I can only give you the hint that "Couldn't parse multi-status response" sounds like the SimpleXML library is not fully embedded and thus reflection fails.
