### ISSUE TITLE
Synchronization process is only started after creating the account

### ISSUE THREAD

**Issue by colegota** [bitfireAT/davdroid#488]
Hi!

I'm using Davdroid (Fdroid version) in a CyanogenMod 11 system connected to an Owncloud server calendar.
Privacy option it's deactivated for Davdroid. But it just synchronize when I create account, and later I made changes both in AOSP calendar and in Owncloud but there are not reflected on the other side.

Going to Accounts->Davdroid and forcing manual syncing it remains with the same old sync date and nothing changes.

Any help it's welcome.

Regards,
Colegota

**Comment by devvv4ever** [comment]
Did you move DAVdroid to a SDcard?

**Comment by colegota** [comment]
No. It's just as Fdroid installed it.

**Comment by rfc2822** [comment]
This doesn't sound like a DAVdroid issue, but rather like synchronizing accounts is deactivated on your device or something like that.

Does synchronizing other accounts (not DAVdroid, but email for instance) work?

Is synchronizing accounts enabled? Did you restrict mobile data usage? Are you in a WiFi networking?

**Comment by colegota** [comment]
> Does synchronizing other accounts (not DAVdroid, but email for instance) work?
Yes, K9 mail works fine and other accounts as Andstatus (social network client) synchronize also.

> Is synchronizing accounts enabled? 
Yes, the icon on top status bar it's on.

> Did you restrict mobile data usage? 
No.

> Are you in a WiFi networking?
Not sure about this question. When I'm at home I use my router's wifi connection to Internet and when away then mobile data.

**Comment by rfc2822** [comment]
When the sync process isn't even _initiated_, I guess there's little DAVdroid can do (apparently it's not even started).

I haven't seen this problem yet, so I really think there's something wrong with your device settings.

Can you try on another device?

**Comment by colegota** [comment]
Sorry, no more devices.

If you have some idea about what I can check in my device settings I'll try it.

Anyway, thanks for your  help! :)

**Comment by colegota** [comment]
Hi!
I've remember that I have another Owncloud server (via openmailbox.org), so I upload there my calendar, synchronize it, added a new event at my phone and then it was reflected at the server so you are OK that **Davdroid works fine** and it's something at my end.

Probably the problem was that in my server there is an Owncloud 5 old version while the one in openmailbox.org it's 7.

While also noted that when creating Davdroid account at the phone it ask for an account name and it suggest for use an email account. First time I just give a no email account but just a word like "myaccount" and now I fill it with an email like "me@myserver.com".

It's necessary that account name must be a real email account?

**Comment by rfc2822** [comment]
It's not necessary, but the Android Calendar app fills the ORGANIZER field of an event with the account's name. DAVdroid writes "mailto:" + the ORGANIZER field to the [ORGANIZER property](http://www.kanzaki.com/docs/ical/organizer.html). So if you use ORGANIZER and attendees, make sure you use the organizer email address as account name. It may also be that you can't edit events when the ORGANIZER differs.
