### ISSUE TITLE
CertPathValidatorException although certificate has been added with CAdroid

### ISSUE THREAD

**Issue by siick** [bitfireAT/davdroid#499]
Hello everybody.
I'm a long time user of your app, very useful but today i had to face a problem with the sync of my calendar on Owncloud.
Today i've changed my cert, imported it with CADroid, it works, i can see my cert in the security option of Android.
I had one DAVDroid account for my contact and another one for my calendar. Before the change of my cert, it was all OK.
Now, my contact is syncing normally, but my calendar isn't!
I've tried to delete my calendar account and create a new one but still the same error :
"Synchronization failed
xxx@xxxx.xx(it's my mail that i used to add the calendar account it's not like that, but i don't want to show it)
javax.net.ssl.SSLhandShakeException:
java.security.cert.CertPathValidatorException : Trust anchor for certification path not found.
at
org.apache.harmony.xnet.provider....."
How i can have a SSL and Cert exception with one account and not the other one??? 
I precise that my contact and my calendar are on my Owncloud on the same server with the same owncloud account.
Thanks for your future answer.

**Comment by rfc2822** [comment]
Does DAVdroid accept the certificate when you add the account again? (You don't need to delete the old accounts for trying.)

> How i can have a SSL and Cert exception with one account and not the other one???

That should indeed not be possible.

> I precise that my contact and my calendar are on my Owncloud on the same server with the same owncloud account.

You may also add contacts and calendars as one single DAVdroid account using .well-known paths.

**Comment by siick** [comment]
Ok, the problem is solved and it's not what i was thinking about.
I've deleted the accounts to create one single account as you said.
The only difference is that i've used a different email to link it to my calendar (every try before i had used the same email). And now it's working. I don't have the error message anymore. Anyway, i still don't know why i had a CertPathValidatorException for that....
Keep up the good work with this app.

**Comment by rfc2822** [comment]
Ok, good to hear that it now works for you.
