### ISSUE TITLE
changed calendar colour | crash on sync

### ISSUE THREAD

**Issue by leoauri** [bitfireAT/davdroid#500]
Since changing the colour of a calendar with solcalendar every attempted calendar sync reports "unfortunately davdroid has stopped", calendar not synced..
On
Fairphone 1 / Fairphone OS 1.3 / Android 4.2.2

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

I couldn't reproduce this issue.

**Comment by rfc2822** [comment]
Any news on this?
