### ISSUE TITLE
Contacts shown as unknown in default Android SMS notifications

### ISSUE THREAD

**Issue by mcassaniti** [bitfireAT/davdroid#501]
Hi,
When I receive an SMS on my Android 4.4.2 phone it shows the contacts name as unknown in the notifications (not the SMS application). When I go to people it does however show the name. Is there a property (e.g.: FN) that I'm missing from my contacts?

**Comment by rfc2822** [comment]
I don't know? I don't have this problem.

It sounds like your raw contacts have not yet been aggregated. Is this behaviour consistent or only directly after you add a DAVdroid account?

**Comment by mcassaniti** [comment]
It is consistent. A typical contact layout is:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Inverse inc.//SOGo Connector 1.0//EN
UID:C659F12F-50C0-0001-5C60-D700C62E158D
N:*Lastname*,*Firstname*
FN:*Full Name*
TEL:TYPE=cell:+61 444 444 444
```

Having said that, I did notice that a contact I thought had a number in my CardDAV backend did not seem to have the TEL: line at all until I modified it. I gather this is what you meant by aggregation.

**Comment by rfc2822** [comment]
> I gather this is what you meant by aggregation.

Yes, if two contacts have the same phone number, they are by default aggregated by Android. See http://android.stackexchange.com/a/21711.

So does it work for you now?

**Comment by mcassaniti** [comment]
It seems I was a bit quick off the mark. The number did appear in the CardDAV backend, but it helps if I run the DB query properly (vCard data was truncated). I previously removed all Google contacts excluding one from Google itself, and the Android people app is configured to show only my DAVdroid contacts. At this stage the phone is showing the contact name as unknown in the notifications section when an SMS is received __unless__ it is the Google contact.

**Comment by rfc2822** [comment]
I guess it is an issue of your Contacts provider or other firmware components. Many people, including me, use DAVdroid as their only contacts source and contact names are shown everywhere correctly.

Which firmware do you use? May the aggregation and/or SMS and/or phone book settings be cluttered?

I'm sorry that I can't give you more assistance but this is not a DAVdroid issue.

**Comment by mcassaniti** [comment]
Ummm, you know when you have to tell someone you are about to go put your head in the sand from embarrassment? This is one of those times. I somewhat forgot that I was also using another notification app. I'll need to talk to them.
