### ISSUE TITLE
Getting "400 Bad request" using versions newer that 0.7.3 on sync attempts 

### ISSUE THREAD

**Issue by IvanRossi** [bitfireAT/davdroid#502]
When upgrading to versions newer that 0.7.3 (from f-droid.org repo) any sync attempt with my owncloud provider (my.owndrive.com) return a "400 Bad request"
Android version is 4.4.2 (x86) on Asus Zenfone 5 (ASUS_T00J)

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

I can understand that you think DAVdroid is the cause, but "400 Bad request" sounds like a server error to me.

**Comment by IvanRossi** [comment]
Will try to get as much info as possible although my owncloud is a SaaS service, so i have no access to logs. 
Anyway I have to say I am skeptical about a server issue, since by _downgrading_ to 0.7.3 (from f-droid.org) I am now able to sync again...

**Comment by IvanRossi** [comment]
it seems that removing the app and reinstalling it to the latest version (0.7.6 from f-droid) solved the issue. Thus probably something related to my terminal...
Thank you for the attention anyway

**Comment by DamageIncorporated** [comment]
I'm here to confirm the error, I've hat the same problem with posteo.de (contacts okay, but error occured when syncing calendar afterwards). After downgrading, in my case to version 0.7.2 f-droid, the issue was gone.

I'll try the uninstall/reinstall solution mentioned by @IvanRossi  and if problems persist in my case, provide [detailed information](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) on this.

**Comment by DamageIncorporated** [comment]
I think the uninstall/reinstall approach solved it for me too. automatic as well as manually triggered syncronisations work without any notifications and my data is still there ;-)

Thanks!

**Comment by devvv4ever** [comment]
Just a small addition: I've found that posteo.de sometimes seems to block requests or so. I don't know exactly but sometimes it's not working or updating while we're testing before a new release. Hoewever: in all cases, after some time, snyc works again without problems.

**Comment by gour** [comment]
I had the same issue with 0.7.7 using my own instance of OC server and uninstall/re-install helped, so it seems there is some issue with davdroid...

**Comment by IvanRossi** [comment]
It seems that there are many other bugs that are possibly duplicates of this one: #411, #427, #508.

**Comment by rfc2822** [comment]
@IvanRossi Why did you re-open this issue? Did you experience problems again?

**Comment by IvanRossi** [comment]
no just wanted to add some references, seems i clicked the wrong button to post my comments..
