### ISSUE TITLE
0.7.6 Wrong timezone for newly created all-day events

### ISSUE THREAD

**Issue by basc** [bitfireAT/davdroid#503]
I just upgraded from DAVdroid version 0.7.2 to 0.7.6 and created a new all-day event in aCalendar.
The newly created event was syncing to my owncloud server and after syncing i reopen that all-day event in aCalendar.
It is no longer an all-day event.
It is now starting from today 02:00 am to tomorrow 02:00 and the timezone for that event is showing a British timezone.
My timezone on my device is Middle European Summertime (GMT+2) and all other events are correct, only the newly created all-day event is showing a British timezone.

If i create a new event (not all-day) starting from i.e. 14:00 to 15:00 pm there is no problem.
After syncing the right timezone is displayed and starting time is still 14:00 pm.

After that i reinstalled DAVdroid 0.7.2 and created an all-day event again.
After syncing to owncloud the event is correct. It is all-day and correct timezone.

So only all-day events are affected and only in DAVdroid 0.7.6.
Going back to 0.7.2 is a workaround.

Does anyone else can confirm and reproduze this problem?

My configuration:
DAVdroid 0.7.6 from F-Droid
LG Nexus 5 running Android 4.4 (CyanogenMod 11)
OwnCloud 8.0.3
aCalendar

**Comment by rfc2822** [comment]
Thanks for reporting. This regression bug in handling all-day events has been fixed.

**Comment by basc** [comment]
Wow, that was quickly. Thank You!
