### ISSUE TITLE
ownCloud syncing

### ISSUE THREAD

**Issue by Emil-V** [bitfireAT/davdroid#508]
Hi,
I'm not sure if this is an DAVdroid or ownCloud issue, or that I am doing something wrong... So please excuse me if I'm at the wrong place here.

I'm trying to sync my contacts from ownCloud with DAVDroid. I copied the link from the ownCloud service eg.
https://cloud.openmailbox.org/remote.php/carddav/addressbooks/my.email%40openmailbox.org/contacts
I can connect and select the contactlist and birthday calendar, but the syncing doesn't seem to work. Android indicates syncing happens, but I cannot see my Android contacts in ownCloud or vice versa. I enabled the contactlist in my contact list.
I tried this with 2 different ownCloud providers, but the result is the same. ownCloud 7.0.3 and 7.0.5 were used.

Am I doing something wrong, or is this a bug in DAVdroid/ownCloud?

Kind regards,

Emil

**Comment by dper** [comment]
What server are you trying to sync to? What version of DAVdroid are you using? It shouldn't matter, but is there a specific reason you're using OwnCloud 7 instead of OwnCloud 8?

**Comment by Emil-V** [comment]
What server? https://cloud.openmailbox.org/remote.php/carddav/addressbooks/my.email%40openmailbox.org/contacts
This one for example.
I am using DAVDroid 0.7.7. The reason I use OwnCloud 7 is because that's what the cloud provider has.

**Comment by rfc2822** [comment]
> I can connect and select the contactlist and birthday calendar, but the syncing doesn't seem to work. Android indicates syncing happens, but I cannot see my Android contacts in ownCloud or vice versa. I enabled the contactlist in my contact list.

Thanks for your report.

Can you provide detailed steps, [log entries](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs) and maybe a test account to reproduce so that we can identify the problem?

**Comment by rfc2822** [comment]
Any news on this?

**Comment by Emil-V** [comment]
I didn't find any time to look at this. I will provide the things you asked for next week.

**Comment by derkostka** [comment]
I am having a very similar Problem. I use owncloud 8.1 (testing) wich implements sabre-dav 2.1.3 for CardDav. Now my problem is that from 117 contacts, only the first 18 are synced. With Davdroid 0.7 and Owncloud 7, everything went fine.

Where can i get logfiles in davdroid ? Does logcat work ? Thanks !

**Comment by Emil-V** [comment]
Sorry for the late answer.
I made a test account at openmailbox.org:
testdavdroid@openmailbox.org
testdroidtest
The account has 2 people in the contact list, but they do not show up in my contact list on android, nor do my android contacts show up in Owncloud.
I made the logfile with ```adb logcat | egrep '^(E/)|(./davdroid)|(./HttpClient)|(./Wire)'``` while syncing, It's rather large though.
https://gist.github.com/Emil-V/148fc8e2fa6918f6d5b3

**Comment by rfc2822** [comment]
Can you please check whether this issue is still present with DAVdroid 0.8.1?

**Comment by derkostka** [comment]
I checked now on a HTC One at Android 5.0.2 against owncloud 8.1.0 ... Unfortunately still only 18 out of 100 contacts are synced, also no error is thrown.

CardDav App does it's Job however .. What can i do to help you investigate my issue ? Thanks !

**Comment by Emil-V** [comment]
The issue is still present with DAVdriod 0.8.1

**Comment by rfc2822** [comment]
Is this the same as #578?

**Comment by Emil-V** [comment]
I don't think so, as  #578 seems to be a bug introduced ownCloud 8.1. I used ownCloud 7.0.3 and 7.0.5.

**Comment by rfc2822** [comment]
Ok, I'll have a look at it as soon as I find some time.

**Comment by rfc2822** [comment]
#578 is caused by https://github.com/owncloud/contacts/issues/581 which is present since at least OwnCloud 6.0.3.

Please follow up in the issues mentioned above.
