### ISSUE TITLE
Old timezones data

### ISSUE THREAD

**Issue by urusha** [bitfireAT/davdroid#509]
Timezones data of davdroid is really old, so events created in several timezones (e.g. MSK) are displayed with wrong time.
Here is the commit at ical4j-master branch, fixing this: https://github.com/ical4j/ical4j/commit/4001177936daefa37ad7d498429928158670a445
So, please, include this fix in the next release.
Thank you!

**Comment by rfc2822** [comment]
Can this ical4j version included with gradle? Currently,
```
dependencies {
  compile 'org.mnode.ical4j:ical4j:1.0.6'
}
```
is used. Also, this commit seems to be for ical4j/2 which is still alpha (DAVdroid will use ical4j 1.0.x until 2.0 is released).

**Comment by urusha** [comment]
May https://github.com/ical4j/ical4j/tree/ical4j-1.x-maintenance branch be used? Than this commit could be applied to it.
Also, I've made patch for 1.0.6: https://gist.github.com/urusha/591c02512cd0684d48b3#file-0001-updated-zoneinfo-to-tzdata2015c-patch 
Gradle seems to support applying standalone patches.
And here is the new ical4j issue: https://github.com/ical4j/ical4j/issues/34

**Comment by rfc2822** [comment]
> Gradle seems to support applying standalone patches.

How? I haven't seen anything on how to use source repositories with gradle without using a whole new subproject (which I'd like to avoid).

However, as soon as there's a new ical4j 1.0.x version, the DAVdroid dependency can be easily updated.

**Comment by urusha** [comment]
I'm not a gradle specialist, but may be this: http://stackoverflow.com/questions/17064086/how-do-i-apply-a-patch-file-in-gradle could be used? Since all users in the countries with changed timezone can not use this app normally, I think it's worth fixing.
gist.github.com has eaten '\r' newlines from the patch. If it's needed I could upload it to another place.

**Comment by rfc2822** [comment]
DAVdroid now uses ical4 2.0-alpha1 since a796a1e9b38a22a943314183957ac4c12af82520. However, the new timezones are still not in ical4j 2.0-alpha1. As soon as a new ical4j version is release, the time zones will be updated.

**Comment by rfc2822** [comment]
The next DAVdroid release will contain ical4 with the tzdata2015c time zones. However,

1. as far as I can see, the last update for Moscow is from 2011 even in the tzdata2015c database,
2. the system time zones (and thus the ones in your calendar app) are not affected by this, meaning that imported events should have the correct time as far as DAVdroid is involved in calculating, but the system and calendar apps will still use the old time zone definitions. This can only be fixed by a firmware update.

**Comment by urusha** [comment]
Thanks! Waiting for release.
1. MSK timezone has been changed with 2014h release.
2. On old firmwares system timezone can be changed to the zone with the correct time (for current MSK it's +3), so the offset between ICS time data and system time disappears. It's a workaround. Opposite to this, there is no way to view and create events with the correct time simultaneously (using an old ical4j tzdata). Еvents created using software with an up-to-date timezone data (and correct timezone set) are displayed wrong with an old ical4j tzdata, until you set your system timezone to another value to remove an offset. But if you set so, new events created on this system will be displayed wrong on other systems/software. The only way to fix this was repacking DAVdroid with an updated tzdata. But now, 0.8.2 is coming :)

**Comment by rfc2822** [comment]
@urusha: https://github.com/ical4j/ical4j/blob/master/src/main/resources/zoneinfo/Europe/Moscow.ics
Is this the correct & up-to-date definition? I can see 2014 somewhere but I don't know… it should be from 2015c

**Comment by urusha** [comment]
Yes, it's correct. At RDATE:20141026T020000 the time was moved from +4 to +3 and that's the current timezone.

**Comment by rfc2822** [comment]
Ok thanks. Unfortunately, I didn't manage the self-compiled ical4j to get working (see https://github.com/ical4j/ical4j/issues/29), so we'll have to wait for the next ical4j release (maybe with DAVdroid 0.8.3).
