### ISSUE TITLE
Cannot edit events on Galaxy S3

### ISSUE THREAD

**Issue by may-bee** [bitfireAT/davdroid#510]
I currently do not know, whether this is a feature request or a bug. The following holds:
After synchronizing my contacts on my Galaxy S3 (GT-I9300 / Android 4.3 / Build JSS15J.I9300XXUGOC1) with my Owncloud 8.0.3 server hosted on a kvm virtualized root server, I can see all details in the contact view. Especially events are correctly synchronized and shown for each contact on the device.
But when trying to edit the contact, events are not shown in the edit view and thus cannot be changed or inserted.

**Comment by devvv4ever** [comment]
Hello,
DAVdroid is a sync adapter only. So it only reads and writes the data it gets from the server or the android contacts storage. I think this could be a limitation of your contacts app. What kind of Android device and and firmware do you have? You could try an unbranded contacts app named "True Contacts" and see if it works with it.

**Comment by may-bee** [comment]
Hi,
I have the standard contact app from Samsung. I tried True Contacts and how impressing... it works.
So again let me state this: I hate Samsung for what they are doing with Android on their devices!

Thanks :)

**Comment by devvv4ever** [comment]
You're welcome ;) And I fully agree - vendors really do a lot of shitty things with branding... I'm currently using the standard contacts app on the Galaxy S6 with Android 5. It works here - so they're at least learning a bit from mistakes of previous versions...
