### ISSUE TITLE
contact sync ist not working while calendar sync works

### ISSUE THREAD

**Issue by bummi2k** [bitfireAT/davdroid#511]
I am using a Sony Xperia z3 compact with Android 5.0.2 and trying to sync that with a local Horde 5.2.6 installation in a VirtualBox. When adding a davdroid account the app successfully finds my adressbook and my calendar url. The sync works only for calendar. The adress book in the phone stays empty after sync. If I try to add a contact in the Contact App the phone states sucess, but the adressbook stays empty. The CardDAV app from Marten Gajda is working fine.
Any idea on that ?

**Comment by devvv4ever** [comment]
Did you choose "Contacts to display" in the contacts app and select your DAVdroid account?

**Comment by bummi2k** [comment]
Thanks for the extremly fast answer ! I've played a little bit with the contacts app. The option is hidden in the filter settings in the contacts app. There I could switch on the DAVdroid account visibility. 
For me the issue is solved. Thanks a lot.
