### ISSUE TITLE
0.8-beta1 crash while adding account

### ISSUE THREAD

**Issue by snackiz** [bitfireAT/davdroid#513]
I add an account logging in with URL and password and I can choose which contact list and calendar to sync (I have two contact books and two calendars in my account). But as soon as I scroll past the last calendar (or if I rotate the screen), DAVdroid crashes.

**Comment by devvv4ever** [comment]
thanks for testing: if you can reproduce this it would be very important for us to see whats happening in the verbose logs. can you create them for us? here is a small guide: https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by rfc2822** [comment]
Can you please try https://github.com/bitfireAT/davdroid/releases/tag/v0.8-beta2?

**Comment by snackiz** [comment]
With 0.8-beta2 I could add the account and choose what to sync.
When I press the check-button to add the account, DAVdroid crashes, although the account has been created. I will check if I can get some relevant logs tomorrow.

**Comment by rfc2822** [comment]
Can you please try https://github.com/bitfireAT/davdroid/releases/tag/v0.8-beta3?

**Comment by snackiz** [comment]
beta3 works, thank you.
