### ISSUE TITLE
Remove old events

### ISSUE THREAD

**Issue by ouafnico** [bitfireAT/davdroid#514]
Hello

I'm using davdroid to sync owncloud calendar.
The only problem I've got is when I remove an event on owncloud, even after sync on davdroid, the event is still present.

How can we tell davdroid to remove obsoletes events ?

Thanks

**Comment by devvv4ever** [comment]
hi, it normally should remove these events. for me, when testing with owncloud, it takes some time until the database is updated, it's not instantly. did you wait a minute or so after trying to sync again? 

can you send verbose logs so that we can take a look at whats happening on the davdroid side?

https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by ouafnico** [comment]
I have waited and refresh but old events still presents. 

I've tried the logs, I only have with errors, this one a lot of time  : 

E/davdroid.DateUtils(21462): Couldn't identify time zone, using UTC as fallback

**Comment by devvv4ever** [comment]
hi again,

davdroid removes it only when you delete it manually. if the events are just old they remain in the database and as a sync adapter DAVdroid syncs them, too. however we want to have an option some time where only events are synced that are +/-X years/months/days from now. 

DAVdroid only syncs the changes every time, not everything. so there is not too much data overhead, except from the inital sync after a new setup.

**Comment by ouafnico** [comment]
It's a real suppression. The event is removed from owncloud, but still exist on android after davdroid update.

**Comment by rfc2822** [comment]
Is it possible that you provide logs or a test account + steps to reproduce? We can't take a look when we can't reproduce the issue.

**Comment by ouafnico** [comment]
I can't :s 

I'm using this way 
- Outlook export to webdav folder the ics file (owncloud)
- The calendar is imported to owncloud every X minutes
On owncloud, all changes are successfully applied  : when I remove an event on outlook, it is removed on owncloud
- Davdroid get the calendar of owncloud on android phone : but never remove old events :s

**Comment by rfc2822** [comment]
Without logs and/or a test account, I can't reproduce the issue or be of any help.

Do you think it's really the fault of DAVdroid (deleting events from OwnCloud works for other installations) and can you suggest a way how to analyze this problem?

**Comment by ouafnico** [comment]
When I try create a new task on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date

when I remove the task on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date (correctly removed)

When I try create a new meeting on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date

when I cancel the meeting on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date (correctly removed)

When I try create a new recurrent meeting on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date

when I cancel one future meeting for the recurrent meeting on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date (correctly removed)

when I cancel one old meeting for the recurrent meeting on outlook
- after the sync owncloud is not up to date
- so davdroid can't be up to date too..

when I cancel all the recurrent meeting on outlook
- after the sync owncloud is up to date
- after the sync davdroid is up to date (correctly removed)


So maybe the problem is between outlook and the owncloud sync :s sorry
