### ISSUE TITLE
Cannot set sync period. Sync still disabled

### ISSUE THREAD

**Issue by andrkac** [bitfireAT/davdroid#516]
I cannot bring davdroid to work. Manual sync works like a charm, but for all accounts (caldav, carddav) synchronization is still disabled. Tried to change to manual only and to periodical syncing again, but no effect.
Davdroid is 0.7.7 and the lates community version of owncloud as the backend

**Comment by rfc2822** [comment]
Sounds like you disabled synchronization system-wide (not just for DAVdroid). Could that be the cause?

**Comment by andrkac** [comment]
Yes. I've found it few minutes after last message. 
Guess, that my kid has changed it. But I don't know why, it's not so easy :)
