### ISSUE TITLE
org/dmfs/provider/tasks/UriFactory.java is a symbolic link

### ISSUE THREAD

**Issue by ducktayp** [bitfireAT/davdroid#517]
The file app/src/main/java/org/dmfs/provider/tasks/UriFactory.java is a symbolic link to /home/rfc2822/Entwicklung/Android/task-provider/src/org/dmfs/provider/tasks/UriFactory.java (the actual contents appear to be missing from the repository).

**Comment by rfc2822** [comment]
It's linked to https://github.com/dmfs/task-provider/tree/master/src/org/dmfs/provider/tasks/UriFactory.java. You can fetch it from there.

**Comment by ducktayp** [comment]
Ah. Thanks. I suggest that this file be copied over, or that the task-provider repository be used as a sub-repository; otherwise the code is no longer self-contained (and in any case, the link is an absolute one that explicitly points to your home directory...)

**Comment by rfc2822** [comment]
The file will be copied.
