### ISSUE TITLE
changes recurring todos back to single-item todos

### ISSUE THREAD

**Issue by jelmer** [bitfireAT/davdroid#521]
when syncing back todo items that recur, davdroid strips them down to once-happening items and removes all records that the item was completed in the past.

The item on the "master" entry that is removed is "RRULE:FREQ=DAILY" in my case.

**Comment by rfc2822** [comment]
Recurring todos are not supported by the Tasks app and thus not by DAVdroid.

**Comment by jelmer** [comment]
Even if it can't display the recurrence, silently removing it seems... suboptimal and surprising.

**Comment by jelmer** [comment]
Another option might be to simply skip any recurring items when pulling in new items; that is at least less destructive.

**Comment by rfc2822** [comment]
Merged with #520.
