### ISSUE TITLE
Change sample URL in account creation dialog to have a trailing slash

### ISSUE THREAD

**Issue by dassams** [bitfireAT/davdroid#522]
Hi,
I try to set-up an account for Horde5 on a CM12 (Lollipop) phone.
I chose the Base-URL method and choose https, enter my host (just the base URL like mail.abc.com), username (it's mail address style like me@bla.com) and password.
Next I expected to be able to click next ("->") but I can't - nothing happens/it is no clickable.
Well-known URL is setup and tested.

What am I doing wrong? How could I trace this issue?

Markus

**Comment by rfc2822** [comment]
If the Next button is not clickable, the URL is not (yet) valid. Does it maybe contain underscores or other invalid characters in the hostname?

**Comment by dassams** [comment]
Thanks for the hint.

No, it is just a simple URL (mail.mwagner.info) - so that's what I
entered: "https://" from the drop-down and mail.mwagner.info in the
hostname.
Can I/Should I put the whole address to the RPC, principals in there, too?!

On 05/30/2015 12:58 PM, rfc2822 wrote:
>
> If the Next button is not clickable, the URL is not (yet) valid. Does
> it maybe contain underscores or other invalid characters in the hostname?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitfireAT/davdroid/issues/522#issuecomment-107021306>.
>


-- 
Markus Wagner • Römerstraße 39 • 64291 Darmstadt
mobil: +49 (0)179-5481432 • fon: +49 (0)6151-3929440 • mail:
markus@mwagner.info

**Comment by dassams** [comment]
Hi, I just fiddled a bit more with the URL. I had to add an extra ("/") at the end.
This is in contrary to the example entry btw.

**Comment by rfc2822** [comment]
Reverted the change because on my test devices, I don't need a trailing slash.
