### ISSUE TITLE
Lollipo 5.0.2

### ISSUE THREAD

**Issue by hitam4450** [bitfireAT/davdroid#529]
Habe das selbst signierte Zertifikat vom Server auf meinem Tab S 8.4 mit Lollipo 5.0.2 importiert
davdroid kann trotzdem sich nicht mit dem Server verbinde ! Warum nicht??
Was ist eine Zertifikatskette? Das verstehe ich nicht!!!
Gruss, hitam4450

**Comment by devvv4ever** [comment]
Um welchen Host geht es denn?

**Comment by hitam4450** [comment]
Sorry, Host ist OC 8.03!

Am 03.06.2015 um 10:26 schrieb devvv4ever:

**Comment by hitam4450** [comment]
Sorry, Host ist OC 8.03, OS DEBIAN 8.0, Jessie !


Am 03.06.2015 um 10:26 schrieb devvv4ever:

**Comment by devvv4ever** [comment]
Ich meinte eigentlich den Hostname/domainname, nicht den Server selbst ;-)

**Comment by hitam4450** [comment]
Bei meinem Netzwerk gibt es nur feste IP Adressen!

**Comment by hitam4450** [comment]
Alles Ok!
