### ISSUE TITLE
Baïkal group calendars not shown

### ISSUE THREAD

**Issue by jplitza** [bitfireAT/davdroid#530]
When scanning for calendars, my DAVDroid 0.8 from F-Droid does not show group calendars. The server uses Baïkal, although with a custom frontend for creating calendars and such, and because I don't administrate it, I don't know the version (maybe it is visible from the [logs](https://gist.github.com/ab8538c561ba7a78c3be)?)

I had a look at #345, but well-known path detection is not supported by the server.

**Comment by untitaker** [comment]
I suppose this is the same as #528 but AFAIK Baikal doesn't even have group calendars. Or are we talking about Baikal 2?

**Comment by rfc2822** [comment]
Please follow up in #439.
