### ISSUE TITLE
not syncing calendar in owncloud 8

### ISSUE THREAD

**Issue by mr-gosh** [bitfireAT/davdroid#537]
i've switched from caldavsync to davdroid - and everything works (contacts, tasks) but the main calendar.

i've deleted all reoccurring events - but still it doens't sync fully.

i can't see any entries from the server, but local entries get synced sometimes.
how do i generate logs for further investigation?

davdroid 0.8 (from f-droid)
android 4.4 / 5.0.2 / 5.1.1

in thunderbird, evolution, ios and caldavsync on android everything works... :(

**Comment by devvv4ever** [comment]
hi, we need the logs from your phone. here is a small guide on this: 

https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by mr-gosh** [comment]
![tmp_1288-screenshot_2015-06-07-08-28-34314868588](https://cloud.githubusercontent.com/assets/3028703/8022967/f5962e36-0cf3-11e5-80b8-2e43c45bb503.png)

Here at first a screenshot - seems to be ssl related. My server uses a cacert certificate and the root ca is imported on all devices (and it worked some time ago)

**Comment by rfc2822** [comment]
"Read error: Connection timed out" means that there was a timeout when reading from the server. Maybe your server responds too slow? Can you check the server logs to see how long the requests take?

**Comment by mr-gosh** [comment]
I'll try to get these numbers BUT the reason will be the huge number of entires (therefore i killed the reoccuring events).
But the other sync adapters can manage this to the same server and the same calendar. I tried Caldavsync and Calendar ICS adapter - https://f-droid.org/app/de.k3b.android.calendar.ics.adapter

**Comment by rfc2822** [comment]
> But the other sync adapters can manage this to the same server and the same calendar. I tried Caldavsync and Calendar ICS adapter - https://f-droid.org/app/de.k3b.android.calendar.ics.adapter

These other apps probably use PROPFIND instead of REPORT to query the server. DAVdroid uses REPORT since v0.8 because it's required for different operations and doesn't transfer unnecessary data.

I suggest to ask in an OwnCloud forum what might take that long (after verifying that it's really a timeout on the server; just have a look at `top` and the server logs).

**Comment by rfc2822** [comment]
Please follow up in #539 and https://github.com/owncloud/core/issues/16786.

**Comment by mr-gosh** [comment]
owncloud issue was moved to https://github.com/owncloud/calendar/issues/807
