### ISSUE TITLE
Synology syncing

### ISSUE THREAD

**Issue by Loxa9** [bitfireAT/davdroid#541]
Hi,

First of all please excuse me for my bad english. I bought your app on Android today, and I try to sync it with a CalDAV server on a Synology NAS. It works, but the names of calendars are their url. For exemple : https://ip:port/folders/NAME.
I can't modify it on my NAS. So is it a bug on DAVdroid ?
Thank you for your help.

Guillaume

**Comment by rfc2822** [comment]
If the calendar server doesn't provide a name, [DAVdroid uses the URL path](https://github.com/bitfireAT/davdroid/blob/c8cfbd6b07edf2413bf7f033e141671025b16105/app/src/main/java/at/bitfire/davdroid/resource/ServerInfo.java#L89).

> I can't modify it on my NAS. So is it a bug on DAVdroid ?

Rather sounds like a missing feature on your NAS.

However, the calendar name shouldn't have any impact on functionality. Does sync-ing working as intended?
