### ISSUE TITLE
DavDroid is crashing, while creating an account and turning the device

### ISSUE THREAD

**Issue by nafets** [bitfireAT/davdroid#543]
DavDroid 0.8.0 crashed on a Motorola Moto G (Android 5.0.2) during the creation of the account.
When you enter the address, user or password in landscape mode and then turn the device, that it has to rotate the screen, back to portrait mode, the application crashes.

**Comment by devvv4ever** [comment]
hi nafets,

thanks for the report. I can however not reproduce this on any of our 4 devices. every combination worked. no crashes. can you tell us more specific steps how we could reproduce it?

it seems to be a device-specific problem (maybe with motorola firmware). if you want us to have a very close look at it you need to send us logs from your phone when it crashes. here is a small guide on how to create such logs:

https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs

**Comment by nafets** [comment]
Hi, 

thanks for the fast answer. Currently I don't have access to this device. 
But I'll try to reproduce it on another device and come back to you with the logs.
