### ISSUE TITLE
Contacts are being merged after sync

### ISSUE THREAD

**Issue by DrWuah** [bitfireAT/davdroid#544]
I encountered this problem in previous versions but it still exists in davdroid 0.8.0. I sync with mailbox.org and even multiple phone numbers are no issue for me - they are getting synchronised as they should. My problem is, that sometimes (over night / after a new sync) two contacts get merged into one. For better understanding:

On Server: 
1. Entry: Person A, mobile a, mail a, 
2. Entry: Person B, mobile b, phone b.

On my phone (after sync):
1. Entry: Person A, mobile a, mobile b, mail a, mail b

Which accounts are affected seems random to me. On the mailbox.org server, there are still Person A and Person B separately and unaffected. Several new setups of my account in davdroid only lead to a short-term solution.

**Comment by rfc2822** [comment]
This seems to be an issue of Android contact merging (for instance, see https://code.google.com/p/android/issues/detail?id=4979). DAVdroid synchronizes only raw contacts. Person A und Person B on the server are synced as two raw contacts on your device, but Android may merge them to one "contact" (not: "raw contact"). You can see this when the contact has two DAVdroid icons. In this case, you can split it in the Contacts app.

**Comment by DrWuah** [comment]
Thanks for your answer!
You are right. This is not a problem of DAVdroid, in fact, it's the android contacts behaviour that merges people randomly. Because affected accounts were totally unrelated I thought it was due to synchronizing - thanks for pointing out the solution! The 'split' option in the edit menu of the contacts restores both contacts separately.
