### ISSUE TITLE
DAVdroid 0.8.0 does not sync anymore ("Unfortunately, DAVdroid has stopped.")

### ISSUE THREAD

**Issue by webdb22** [bitfireAT/davdroid#552]
Since some days DAVdroid 0.8.0 does not sync any more (maybe a time-out) with the CalDAV server (Beehive). Now and then I'm receiving a dialog box on my Android saying: "Unfortunately, DAVdroid has stopped." 

It has already worked fine for some weeks while I was testing the functionality. I've tried to set up a new account, I can list the calendars available, but sync does not work any more.

I haven't changed anything on the client, there might have been some security updates on the server infrastructure, but I don't have access to this information or the CalDAV server itself.

Any idea how to fix this?

Thanks!

**Comment by rfc2822** [comment]
Do you have Tasks installed? In this case, you would have to re-install DAVdroid.

**Comment by Parsival1973** [comment]
I was having a similar issue in which 0.8.0 was not syncing anything. I did uninstall it and install tasks to try but did not work. Reinstalled several times still no go. Went back one version and now contacts and calendar syncing working again. I am connecting to eGroupware server on LG G2 D803 with Vanir 5.1.1 Build on it. 

I did not have any crashes or error messages come up with the application.

**Comment by rfc2822** [comment]
* »I did not have any crashes or error messages come up with the application.«
* »DAVdroid 0.8.0 does not sync anymore ("Unfortunately, DAVdroid has stopped.")«

I'm confused. Does it stop (crash) with the "DAVdroid has stopped." message or is there no message?

Could please provide **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)** and/or a test account?

**Comment by rfc2822** [comment]
Please check whether this issue is still present with DAVdroid 0.8.1.
