### ISSUE TITLE
davdroid paid app : but https not working

### ISSUE THREAD

**Issue by me88** [bitfireAT/davdroid#556]
Hello,

I have a shared hosting server in which I use owncloud (+calendar and contacts)

I didn't wanted to buy a ssl certificate. So I get an untrusted certificate.

By using your paid davdroid app:

I try to enter the htts :// mydomain.com/remote.php/caldav

But I get an error message i/o error : hostname in certificate didn't match ...

I have tried to dll your cadroid app but it says "the certificate chain doesn't contain a valid certificate for the host name ..."

However, I have acces to the caldav with https from any browser (chrome, ff ...)

I feel a bit upset to encounter issues as I paid the app ...

Please tell me what to do in order not to use it in plain http !

**Comment by untitaker** [comment]
The error is quite clear on the problem: Your certificate must be issued for the correct hostname. I don't think pinning a certificate against a specific hostname is possible with the way Android's certstore works.

**Comment by rfc2822** [comment]
What is the domain name? Please send the URL to play@bitfire.at if you don't want to post it publicly.
