### ISSUE TITLE
Unfortunately, DAVdroid has stopped (paid version) SQLiteDoneException

### ISSUE THREAD

**Issue by michaelberg79** [bitfireAT/davdroid#557]
I'm using davdroid for many years. But now it stopps syncing at some contacts. 
I cant find any inputerrors which causes the error. For example i try to sync following contact:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//EGroupware//NONSGML EGroupware Addressbook 14.2//DE 
CLASS:PUBLIC
EMAIL;TYPE=WORK:xxxxxxxxx@yxxxxxx.xx
N:Grade;Jens;;Herr;
FN:Herr Jens Grade
ORG:mp messebau;;
TEL;TYPE=CELL,WORK:xxxxxxxxxxxxxxxxx
REV:2015-06-18T16:18:27Z
END:VCARD
```

He stopps with the given error. If i delete the surname "Grade" he does sync it with my device. If i insert it again he raise the error again. There are some other contacts syncing without errors. 

For a other contact i added "Herr" into the "Anrede" field. After this, davdroid is syncing the contact. Its a very stupid behavior. I cant locate the bug without any traces or logfiles.

The same behavior at task syncing. only the calendar sync is working fine.

best regards
Michael

**Comment by untitaker** [comment]
If you recieve a "Unfortunately, DAVdroid has stopped", there is almost certainly some relevant entry in the logcat.

**Comment by michaelberg79** [comment]
i using a new samsung s6 edge unrooted. there is no possibility to read the log with logcat.

**Comment by untitaker** [comment]
`adb logcat` works for non-rooted phones as well I think.

**Comment by untitaker** [comment]
Ahh I now have seen that this has changed with JellyBean... :(

**Comment by michaelberg79** [comment]
this is the egroupware logfile for the webdav request without errors.

*** 178.25.22.229 2015-06-18T19:56:15+02:00
GET /egroupware/groupdav.php/michaelberg/addressbook-Messebau/276.vcf HTTP/1.1
Accept: text/vcard;q=0.8, text/vcard;version=4.0
Host: egroupware.famberg.de
Connection: Keep-Alive
User-Agent: DAVdroid/0.8.0
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Date: Thu, 18 Jun 2015 17:56:15 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.5
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-Dav-Powered-By: EGroupware 14.2 CalDAV/CardDAV/GroupDAV server
Content-Encoding: identity
ETag: "276:6"
Content-type: text/x-vcard; charset=utf-8
Cache-Control: maxage=1
Pragma: public
Content-Length: 326
X-WebDAV-Status: 200 OK

BEGIN:VCARD
VERSION:3.0
PRODID:-//EGroupware//NONSGML EGroupware Addressbook 14.2//DE
CLASS:PUBLIC
EMAIL;TYPE=WORK:p.kickner@googlemail.com
N:Kickner;Petra;;Frau;
FN:Frau Petra Kickner
ORG:;;
TEL;TYPE=HOME,VOICE:0049871923330
UID:addressbook-276-b945f47cb927aaea6f2b32c9bca97e9d
REV:2015-06-18T17:56:09Z
END:VCARD
*** GET /michaelberg/addressbook-Messebau/276.vcf --> "200 OK" took 0.035 s

This is the the logfile for the request with error:

     <D:getetag>"486:1"</D:getetag>
    </D:prop>
   <D:status>HTTP/1.1 200 OK</D:status>
  </D:propstat>
   <D:propstat>
    <D:prop>
     <ns2:getctag/>
   </D:prop>
   <D:status>HTTP/1.1 404 Not Found</D:status>
  </D:propstat>
 </D:response>
 <D:response xmlns:ns0="urn:uuid:c2f41010-65b3-11d1-a29f-00aa00c14882/" xmlns:ns2="http://calendarserver.org/ns/">
  <D:href>/egroupware/groupdav.php/michaelberg/addressbook-Messebau/489.vcf</D:href>
   <D:propstat>
    <D:prop>
     <D:getetag>"489:8"</D:getetag>
    </D:prop>
   <D:status>HTTP/1.1 200 OK</D:status>
  </D:propstat>
   <D:propstat>
    <D:prop>
     <ns2:getctag/>
   </D:prop>
   <D:status>HTTP/1.1 404 Not Found</D:status>
  </D:propstat>
 </D:response>
</D:multistatus>
*** PROPFIND /michaelberg/addressbook-Messebau/ --> "207 Multi-Status" took 0.031 s

*** 178.25.22.229 2015-06-18T20:03:54+02:00
GET /egroupware/groupdav.php/michaelberg/addressbook-Messebau/489.vcf HTTP/1.1
Accept: text/vcard;q=0.8, text/vcard;version=4.0
Host: egroupware.famberg.de
Connection: Keep-Alive
User-Agent: DAVdroid/0.8.0
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Date: Thu, 18 Jun 2015 18:03:54 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.5
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-Dav-Powered-By: EGroupware 14.2 CalDAV/CardDAV/GroupDAV server
Content-Encoding: identity
ETag: "489:8"
Content-type: text/x-vcard; charset=utf-8
Cache-Control: maxage=1
Pragma: public
Content-Length: 243
X-WebDAV-Status: 200 OK

BEGIN:VCARD
VERSION:3.0
PRODID:-//EGroupware//NONSGML EGroupware Addressbook 14.2//DE
CLASS:PUBLIC
N:Grade;Jens;;Herr;
FN:Herr Jens Grade
ORG:;;
UID:addressbook-489-b945f47cb927aaea6f2b32c9bca97e9d
REV:2015-06-18T18:03:41Z
END:VCARD
*** GET /michaelberg/addressbook-Messebau/489.vcf --> "200 OK" took 0.038 s

there seem no differences between the requests. the errer should be at davdroid.

**Comment by rfc2822** [comment]
What is "the error", apart from not syncing the contact? Do you get an error message via Android notifications? Does DAVdroid crash ("DAVdroid has stopped")?

**Comment by michaelberg79** [comment]
I get "davdroid has stopped" syncing some contacts. He stop than. He synced 10 of 80 contacts. If i am deleting the contacts davdroid is moving on till the next contact raising the error.

**Comment by michaelberg79** [comment]
i got the logcat running with adb. this is the output of the error:
D/davdroid.DavSyncAdapter(30276): Creating new DavHttpClient
V/davdroid.TlsSniSocketFactory(30276): Setting allowed TLS protocols: TLSv1, TLSv1.1, TLSv1.2
D/davdroid.DavSyncAdapter(30276): Server supports VCard version 3.0
V/davdroid.URIUtils(30276): Normalized URL http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/ -> http://egroupware.famberg.d
e/egroupware/groupdav.php/michaelberg/addressbook-Messebau/
D/davdroid.WebDavResource(30276): Using preemptive authentication (not compatible with Digest auth)
I/davdroid.SyncManager(30276): Remotely removing 0 deleted resource(s) (if not changed)
I/davdroid.SyncManager(30276): Uploading 0 new resource(s) (if not existing)
I/davdroid.SyncManager(30276): Uploading 0 modified resource(s) (if not changed)
D/EnterpriseController( 2921): mIsMarkChainAdded is 0 mIsBlockChainAdded is 0 netId is 0
D/Netd    ( 2921): getNetworkForDns: using netid 524 for uid 10195
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/ -> /egroupware/groupdav.php/michaelberg/addressbook-Messeb
au/
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/
D/davdroid.SyncManager(30276): Last local CTag = 1434650169; current remote CTag = 1434650621
I/davdroid.SyncManager(30276): Fetching remote resource list
D/StatusBar.NetworkController( 3834): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f02054a/com.android.systemui:drawable/stat_sys_wifi_signal
_3 mobileLabel=Vodafone.de wifiLabel="FB Network" emergencyOnly=false combinedLabel="FB Network" mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0204
e4/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f020123/com.android.systemui:drawable/ic_qs_signal_4 mDataDirectionIconId
=0x0/(null) mDataSignalIconId=0x7f0204e4/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x7f02034a/com.android.systemui:drawable/st
at_sys_data_connected_h mQSDataTypeIconId=0x7f02012d/com.android.systemui:drawable/ic_qs_signal_h mNoSimIconId=0x0/(null) mWifiIconId=0x7f02054a/com.android.sys
temui:drawable/stat_sys_wifi_signal_3 mQSWifiIconId=0x7f020138/com.android.systemui:drawable/ic_qs_wifi_3 mWifiActivityIconId=0x7f020517/com.android.systemui:dr
awable/stat_sys_signal_inout mBluetoothTetherIconId=0x7f02052a/com.android.systemui:drawable/stat_sys_tether_bluetooth
D/STATUSBAR-WifiQuickSettingButton( 3834): onWifiSignalChanged enabled=true enabledDesc:"FB Network"
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/ -> /egroupware/groupdav.php/michaelberg/addressbook-Messeb
au/
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/217.vcf -> /egroupware/groupdav.php/michaelberg/addressbook
-Messebau/217.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/217.vcf

V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/246.vcf -> /egroupware/groupdav.php/michaelberg/addressbook
-Messebau/246.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/246.vcf

V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/276.vcf -> /egroupware/groupdav.php/michaelberg/addressbook
-Messebau/276.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/276.vcf

V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/5a9af22d-ab76-49b9-95d9-142ec4507f4c.vcf -> /egroupware/gro
updav.php/michaelberg/addressbook-Messebau/5a9af22d-ab76-49b9-95d9-142ec4507f4c.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/5a9af22
d-ab76-49b9-95d9-142ec4507f4c.vcf
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/26c3eea0-f97e-4d89-92b0-badd3d7dbe24.vcf -> /egroupware/gro
updav.php/michaelberg/addressbook-Messebau/26c3eea0-f97e-4d89-92b0-badd3d7dbe24.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/26c3eea
0-f97e-4d89-92b0-badd3d7dbe24.vcf
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/ada4c241-9205-42e1-8ff1-2b5c057991c5.vcf -> /egroupware/gro
updav.php/michaelberg/addressbook-Messebau/ada4c241-9205-42e1-8ff1-2b5c057991c5.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/ada4c24
1-9205-42e1-8ff1-2b5c057991c5.vcf
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/fdf03bcf-c0e1-4cf8-b89c-f825380e45c8.vcf -> /egroupware/gro
updav.php/michaelberg/addressbook-Messebau/fdf03bcf-c0e1-4cf8-b89c-f825380e45c8.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/fdf03bc
f-c0e1-4cf8-b89c-f825380e45c8.vcf
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/f52cd3f4-5aaf-43f3-ab0f-30cc5ce43aed.vcf -> /egroupware/gro
updav.php/michaelberg/addressbook-Messebau/f52cd3f4-5aaf-43f3-ab0f-30cc5ce43aed.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/f52cd3f
4-5aaf-43f3-ab0f-30cc5ce43aed.vcf
V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/486.vcf -> /egroupware/groupdav.php/michaelberg/addressbook
-Messebau/486.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/486.vcf

V/davdroid.URIUtils(30276): Normalized URL /egroupware/groupdav.php/michaelberg/addressbook-Messebau/489.vcf -> /egroupware/groupdav.php/michaelberg/addressbook
-Messebau/489.vcf
D/davdroid.WebDavResource(30276): Processing multi-status element: http://egroupware.famberg.de/egroupware/groupdav.php/michaelberg/addressbook-Messebau/489.vcf

D/StatusBar.NetworkController( 3834): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f02054d/com.android.systemui:drawable/stat_sys_wifi_signal
_4 mobileLabel=Vodafone.de wifiLabel="FB Network" emergencyOnly=false combinedLabel="FB Network" mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0204
e4/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f020123/com.android.systemui:drawable/ic_qs_signal_4 mDataDirectionIconId
=0x0/(null) mDataSignalIconId=0x7f0204e4/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x7f02034a/com.android.systemui:drawable/st
at_sys_data_connected_h mQSDataTypeIconId=0x7f02012d/com.android.systemui:drawable/ic_qs_signal_h mNoSimIconId=0x0/(null) mWifiIconId=0x7f02054d/com.android.sys
temui:drawable/stat_sys_wifi_signal_4 mQSWifiIconId=0x7f020139/com.android.systemui:drawable/ic_qs_wifi_4 mWifiActivityIconId=0x7f020517/com.android.systemui:dr
awable/stat_sys_signal_inout mBluetoothTetherIconId=0x7f02052a/com.android.systemui:drawable/stat_sys_tether_bluetooth
D/STATUSBAR-WifiQuickSettingButton( 3834): onWifiSignalChanged enabled=true enabledDesc:"FB Network"
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
D/StatusBar.NetworkController( 3834): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
I/davdroid.SyncManager(30276): Fetching 1 new remote resource(s)
V/davdroid.URIUtils(30276): Normalized URL 489.vcf -> 489.vcf
D/davdroid.SyncManager(30276): Adding 489.vcf
D/davdroid.Collection(30276): Committing 3 operations
D/ContactCache( 5253): Contact updated.
D/MyProfileObserver( 5253): onChange()
E/DatabaseUtils( 6628): Writing exception to parcel
E/DatabaseUtils( 6628): android.database.sqlite.SQLiteDoneException
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:768)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.aggregation.ContactAggregator.updateMatchScoresBasedOnNameMatches(ContactAggregator.java:1614)

E/DatabaseUtils( 6628):         at com.android.providers.contacts.aggregation.ContactAggregator.updateMatchScoresBasedOnDataMatches(ContactAggregator.java:1494)

E/DatabaseUtils( 6628):         at com.android.providers.contacts.aggregation.ContactAggregator.pickBestMatchBasedOnData(ContactAggregator.java:1401)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.aggregation.ContactAggregator.aggregateContact(ContactAggregator.java:851)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.aggregation.ContactAggregator.aggregateInTransaction(ContactAggregator.java:531)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.ContactsProvider2.onCommitTransactionInternal(ContactsProvider2.java:3630)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.ContactsProvider2.onCommit(ContactsProvider2.java:3613)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:417)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
E/DatabaseUtils( 6628):         at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:527)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.ContactsTransaction.finish(ContactsTransaction.java:206)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.AbstractContactsProvider.endTransaction(AbstractContactsProvider.java:297)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:245)
E/DatabaseUtils( 6628):         at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:3535)
E/DatabaseUtils( 6628):         at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:294)
E/DatabaseUtils( 6628):         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:192)
E/DatabaseUtils( 6628):         at android.os.Binder.execTransact(Binder.java:446)
E/AndroidRuntime(30276): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(30276): Process: at.bitfire.davdroid:sync, PID: 30276
E/AndroidRuntime(30276): android.database.sqlite.SQLiteException
E/AndroidRuntime(30276):        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
E/AndroidRuntime(30276):        at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
E/AndroidRuntime(30276):        at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:519)
E/AndroidRuntime(30276):        at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:402)
E/AndroidRuntime(30276):        at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:357)
E/AndroidRuntime(30276):        at at.bitfire.davdroid.resource.LocalAddressBook.commit(LocalAddressBook.java:160)
E/AndroidRuntime(30276):        at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:196)
E/AndroidRuntime(30276):        at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
E/AndroidRuntime(30276):        at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
E/AndroidRuntime(30276):        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
V/ApplicationPolicy( 3472): isApplicationStateBlocked userId 0 pkgname at.bitfire.davdroid:sync
I/LoadedApk(30276): getClassLoader :dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/at.bitfire.davdroid-1/base.apk"],nativeLibraryDirectories=[/v
endor/lib64, /system/lib64]]]
D/davdroid.DavSyncAdapter(30276): Closing httpClient
D/AssetManager( 3472): addAssetPath path =/data/app/at.bitfire.davdroid-1/base.apkmapset is 0
D/AssetManager( 3472): addAssetPath path =/data/app/at.bitfire.davdroid-1/base.apk, mapOffset =0
D/AssetManager( 3472): addAssetPath path =/data/app/at.bitfire.davdroid-1/base.apk,elasticAppCookieOffset ={3=0}
I/dumpstate(30299): begin
D/PhoneWindow( 3472): *FMB* installDecor mIsFloating : true
D/PhoneWindow( 3472): *FMB* installDecor flags : 8519682
D/SecContentProvider( 3472): uri = 16 selection = isGoogleAccountsAutoSyncAllowed
I/InjectionManager(28836): dispatchCreateOptionsMenu :com.android.settings.SubSettings
I/InjectionManager(28836): dispatchCreateOptionsMenu :com.android.settings.accounts.AccountSyncSettings
I/InjectionManager(28836): dispatchPrepareOptionsMenu :com.android.settings.SubSettings
D/SecContentProvider( 3472): uri = 16 selection = isGoogleAccountsAutoSyncAllowed
D/MultiWindowConverter( 3472): dismissGuide() : Before attaching the guide view, mForceDismissGuide : false
D/StatusBarManagerService( 3472): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
D/PointerIcon( 3472): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 3472): setMouseCustomIcon IconType is same.101
D/PeopleNotiListenerService( 4037): onEdgeNotificationRemoved() : pkg android,id=1598119898,extra=Bundle[mParcelledData.dataSize=84]
I/art     ( 6628): Explicit concurrent mark sweep GC freed 12884(762KB) AllocSpace objects, 0(0B) LOS objects, 36% free, 27MB/43MB, paused 739us total 84.582ms
D/CrashAnrDetector( 3472): processName: at.bitfire.davdroid:sync
D/CrashAnrDetector( 3472): broadcastEvent : at.bitfire.davdroid data_app_crash
W/ContextImpl( 3472): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1714 com.android.server.analytics.d
ata.collection.application.CrashAnrDetector.broadcastEvent:296 com.android.server.analytics.data.collection.application.CrashAnrDetector.processDropBoxEntry:254
 com.android.server.analytics.data.collection.application.CrashAnrDetector.access$100:60 com.android.server.analytics.data.collection.application.CrashAnrDetect
or$1.onReceive:102
D/SecContentProvider2( 3472): uri = 3 selection = isAccountRemovalAllowed

**Comment by rfc2822** [comment]
Which firmware (Android version and brand) do you use?

**Comment by michaelberg79** [comment]
Gerätename: Galaxy S6 edge
Android-Version: 5.0.2
Kernel Version: 3.10.61-4753955

**Comment by michaelberg79** [comment]
I believe there was some old informations in the contact storage. I deleted data and cache from davdroid and contact storage. I deleted all davdroid accounts and startet from beginning. After this all is fine now.

**Comment by rfc2822** [comment]
Thanks for the update. As this problem hasn't been reported by other people yet, I'll close this report.
