### ISSUE TITLE
Duplicated Contact

### ISSUE THREAD

**Issue by helabenkhalfallah** [bitfireAT/davdroid#560]
Hi,

Davdroid is creating duplicate contacts. 

I create a contact associated to an cardav account. I change the name of this contact. After un-install and re-install of application i got the contact duplicated.The old contact and the edited.

Every time i edit and un-install/re-install of application i got the contact duplicated.

Thanks.

**Comment by helabenkhalfallah** [comment]
Hi,

I have a contact A associated to a gmail account. I synchronise this contact with a cardav account.I got a contact A and an associated contact related to the cardav account. Then i edit the information related to this cardav account (example i change the name from A to A-2). 

After un-install application or delete cardav account all cardav contacts will be deleted (and so the remote name). After re-install or re-connect we will have the old contact A and the edited contact A-2 separated. Before i have the contact A only and the edited contact A-2 is associated to A. After un-install the two contact are separated. 

The result:  i have two contact with the same phone number but with with different name.

**Comment by rfc2822** [comment]
From your description, DAVdroid does **not** create duplicate contacts. DAVdroid creates "raw contacts", as does Gmail. For every person, these two "raw contacts" are aggregated by Android to one "contact".

1. Wait until Android aggregates the contacts (may take some time), or
2. Merge them manually in your Contacts app ("merge"), or
3. Choose "Contacts to show: only DAVdroid" in your Contacts app.
