### ISSUE TITLE
No way to add shared calendar with davical

### ISSUE THREAD

**Issue by urusha** [bitfireAT/davdroid#561]
davdroid (0.8), davical (git)
user1: https://server/caldav.php/user1
user2: https://server/caldav.php/user2
user2 is shared to user1 (user1 has all permissions)
As I see, there is no way to add user2 calendar to davdroid using user1 credentials. Davdroid suggests only user1 calendars/addressbooks, even if URL is filled with "server/caldav.php/user2" . I think before trying well-known URLs, davdroid should check the exact URL for existing profiles.

**Comment by rfc2822** [comment]
Thanks for your report. This is a duplicate of #249, please follow up there.
