### ISSUE TITLE
TLS connection times out

### ISSUE THREAD

**Issue by liobox** [bitfireAT/davdroid#566]
DavDROID 0.8.0 (tried with previous version too)
Nexus 4 running CyanongenMod version 12.1-20150618-NIGHTLY-mako (tried with other 12.1 nighly versions too)
The server is kolabnow.com

I install DavDROID, add the account and seems to sync without a problem (contacts and tasks work perfectly) but DavDROID does not seem to write any event in the Android Calendar.

In the Android Calendar I cannot see any event but those that I create locally from the Android Calendar. Those locally created events are synced without a problem up to the server.

Privacy Guard is completely disabled.

I could only see an incomplete notification: "Synchronization failed - SSL handshake..."

So I collected all the logs following the instructions, and removed the Authorization strings as advised. But for now I prefer to avoid attaching them all because I am a newbie and am not sure if I would leek private data.

Could you help with just the info I've given? In the case I need to attach the logs, can you tell me which ones are really needed so that I do not leek any identifier? Or what other things I should hide besides the characters following "Authorization"?

Thanks!

**Comment by liobox** [comment]
Please see the attached screenshot too. Thank you.
![screenshot_2015-07-02-10-26-24](https://cloud.githubusercontent.com/assets/13063158/8499154/14cc9a5c-217f-11e5-9efa-bf4cb19d8433.png)

**Comment by liobox** [comment]
Please see the attached screenshot.
Thank you.
![screenshot_2015-07-02-10-26-24](https://cloud.githubusercontent.com/assets/13063158/8499238/ff8953fa-217f-11e5-84ac-0faab2049c51.png)

**Comment by liobox** [comment]
Please see the attached screenshot. Thanks.

![screenshot_2015-07-02-10-26-24](https://cloud.githubusercontent.com/assets/13063158/8499791/ba6192f0-2185-11e5-90bc-ad788a04e455.png)

**Comment by rfc2822** [comment]
As the error message indicates, the SSL/TLS connection to the server timed out. It's a network problem. Please try to access the kolabnow DAV URLs in your browser and to set up your DAVdroid account again.

**Comment by liobox** [comment]
I get my calendar's URL from a browser, go to my phone, remove the DavDROID account, set it up with the URL I got from my calendar. Still no change, events are not shown.

**Comment by rfc2822** [comment]
> Still no change, events are not shown.

They can't be shown as DAVdroid can't connect to the server. The SSL/TLS connection times out.

**Comment by liobox** [comment]
Do you know how to solve it?
And, why do contacts and tasks sync without a problem? Aren't they using the same TLS connection?
Thank you.

**Comment by liobox** [comment]
Does this message add any info?
![screenshot_2015-07-06-15-44-18](https://cloud.githubusercontent.com/assets/13063158/8523782/8c6e0ba2-23f7-11e5-94af-70a1ecda8458.png)

**Comment by rfc2822** [comment]
"Connection reset by peer" means that the remote peer (your server) closed the connection before a secure connection could be established. A possible reason could be that your server doesn't allow connections from your mobile IP.

As this is a server and/or networking problem, I'll close this issue here. I think that the some networking forums or the community of your server software could be able to help you.
