### ISSUE TITLE
Contact sync with Kolab Now does not work anymore

### ISSUE THREAD

**Issue by konradrenner** [bitfireAT/davdroid#567]
Hi,
initial contacts sync with Kolab Now does work, but when I change a contact on the server or on the smartphone, the exception which you see on the screenshots occurs. As long as I don't edit a contact, sync works.
This behaviour occured the first the in the version before the actual one.
Please let me know if you need more informations.

![screenshot_2015-06-29-22-44-53](https://cloud.githubusercontent.com/assets/1727807/8425197/9a712160-1f03-11e5-9ac4-589d0093f238.png)

**Comment by rfc2822** [comment]
401 means wrong user name/password. Did you change the password or authentication details?

**Comment by konradrenner** [comment]
No, I didn't change anything. The sync of task and calendar works fine with the same credentials. Only problem is the contact sync.

**Comment by rfc2822** [comment]
Can you please fetch **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)** and see whether the Authorization header is correct? For Basic auth, it's base64 encoded string in the form "<user name>:<password>" (if I remember correctly).

**Comment by konradrenner** [comment]
https://gist.github.com/konradrenner/a8994b2bcdf9409e1992

**Comment by rfc2822** [comment]
Thanks, but these logs are not verbose. You have to do `setprop log.tag.Wire VERBOSE`.

I strongly believe that this is not a DAVdroid issue, but to be sure, we will have to read the wire logs.

**Comment by konradrenner** [comment]
I think the sync fails because google is called. why is it called?

https://gist.github.com/konradrenner/029b6da0eb30c2aff7bc

**Comment by rfc2822** [comment]
Guess it's the same issue as #482.
