### ISSUE TITLE
Syncing fails without warning on TLS CNAME mismatch

### ISSUE THREAD

**Issue by bks2hsj723** [bitfireAT/davdroid#568]
Issue #447 ist still present in 0.8 .
I changed the dns name of my server, without adapting the TLS certificate. The CNAME on the certificate does not match the dns name anymore. davdroid silently failed to sync for a week without me noticing.

I am no expert on the android TLS api, so I cannot tell why the exception is not marked as to be displayed.

Maybe it would be a good idea to display a notification if syncing failed for a prolonged time even if caused by soft errors. If something (dav server, dns, whatever) failed for a long time it would be nice to at least know that something is wrong.

**Comment by rfc2822** [comment]
Thanks for your report. I agree and this is not intended behaviour as certificate errors are hard errors which should be shown. Please follow up in #507.
