### ISSUE TITLE
The import org.apache.http.conn.ssl.SSLConnectionSocketFactory cannot be resolved

### ISSUE THREAD

**Issue by s1mp1c** [bitfireAT/davdroid#570]
Hello, i use Eclipse and i tried to add this class

https://github.com/bitfireAT/davdroid/blob/master/app/src/main/java/at/bitfire/davdroid/webdav/TlsSniSocketFactory.java

in my Android project but it gives me errors about some imports (the ones with asterisk):

	import android.os.Build;
	import android.util.Log;
	*import org.apache.commons.lang3.StringUtils;
	*import org.apache.http.conn.ssl.BrowserCompatHostnameVerifierHC4;
	*import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
	import org.apache.http.conn.ssl.X509HostnameVerifier;
	import java.io.IOException;
	import java.util.Arrays;
	import java.util.HashSet;
	import java.util.LinkedList;
	import java.util.List;
	import javax.net.ssl.SSLSocket;
	import javax.net.ssl.SSLSocketFactory;
	*import lombok.Cleanup;

The errors are like this: **`The import org.apache.http.conn.ssl.SSLConnectionSocketFactory cannot be resolved`**

Can you tell me what's wrong with these imports and how to solve them?

Thank you i advance.

**Comment by rfc2822** [comment]
DAVdroid uses the Apache HttpClient library (Android port), see https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html. DAVdroid's `TlsSniSocketFactory` is working with this library.

**Comment by s1mp1c** [comment]
I did solve the problem importing "httpclient-android-4.3.5.jar" (downloaded from here: http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-android/4.3.5/) in the project.

But there are still dependencies that cannot be resolved:

import org.apache.commons.lang3.StringUtils;
import lombok.Cleanup;

I solved those importing the following JARs:

http://www.java2s.com/Code/JarDownload/common-lang3/common-lang3.jar.zip
https://projectlombok.org/downloads/lombok.jar
