### ISSUE TITLE
Select the color of the calendar

### ISSUE THREAD

**Issue by kallegit1950** [bitfireAT/davdroid#572]
Hi,

I have on one owncloud server multiple users and I want to see their calenders on my Android phone. Unfortunately all calendars are green. What determines this color, can we have in the settings a selection of the color?

Thanks, K.

**Comment by untitaker** [comment]
DavDroid currently doesn't have a setting and uses the ones from the server (with green as fallback).

Setting the color only happens on first sync, an issue is open for syncing the color multiple times: https://github.com/bitfireAT/davdroid/issues/219

**Comment by rfc2822** [comment]
DAVdroid uses the [`calendar-color` property](https://github.com/bitfireAT/davdroid/blob/c6950b1c160bb9a968be555559062141a4106fc0/app/src/main/java/at/bitfire/davdroid/webdav/DavProp.java#L133) returned by the server (with green as fallback).

Set this property on your server and DAVdroid will import the calendars with the colors.

As @untitaker said, the colors are only imported when setting up the account. If you're interested in synchronizing color changes from the server, please follow up in #219. If you just want to set your calendar colors, you may use the [Calendarcolor app](https://f-droid.org/repository/browse/?fdid=ch.ihdg.calendarcolor).
