### ISSUE TITLE
not able to change synchronization interval

### ISSUE THREAD

**Issue by Lioxen** [bitfireAT/davdroid#573]
On my S6, I'm not able to change the synchronization interval. I simply do not see any settings. The only thing I have is "Einstellungen zur Fehlersuche" (Settings for error diagnostics) which shows me two checkboxes for http-compression and for log the network traffic. If I go to my owncloud account, I can switch on/off the sync, nothing else.
I guess this is a restriction on my phone, but it is rooted. May somebody can tell me how I can give davdroid the necessary rights.
Thanks it advance.

**Comment by phy25** [comment]
What version of DAVdroid are you using? Older version is not able to modify the sync interval.

The setting is located at DAVdroid app > "Option" / more button > Settings, or System settings > Sync > "DAVdroid" > Settings.

**Comment by Lioxen** [comment]
You are right phy25, it was version 0.6. After the update to the current version, I can see the settings.
Sorry to bother you.
