### ISSUE TITLE
Widget to start manual sync

### ISSUE THREAD

**Issue by OvOwl** [bitfireAT/davdroid#576]
I dont want to increase the sync intervall but am heavily using multiple clients. So i'd like to sync one specific, or all accounts by pushing a button in the homescreen instead of going all the way into the menu.
Thoughts?

**Comment by rfc2822** [comment]
Sounds like an idea for a separate app, as it's not the scope of DAVdroid to mange sync processes. Maybe there's already one?

**Comment by kallegit1950** [comment]
In the calendar on my device I see in the menu "start synchronization". Seems to be a standard feature fo calendars. Maybe that is sufficient.

**Comment by untitaker** [comment]
This is called Refresh on most ROMs I've used.

On 10 July 2015 12:28:27 CEST, kallegit1950 <notifications@github.com> wrote:
>In the calendar on my device I see in the menu "start synchronization".
>Seems to be a standard feature fo calendars. Maybe that is sufficient.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/576#issuecomment-120363206

-- 
Sent from my phone. Please excuse my brevity.

**Comment by kallegit1950** [comment]
Checked again, on my two Samsung (S5 and xcover 3) devices it is "start synchronization" and "sync", on a Lenovo Yoga 2 tablet this feature seems to be missing. So it might be useful for some devices. OvOwl, what device do you use? Do you have that button in the calendar? I am using this feature heavily as well and I am glad I have it ;-)
