### ISSUE TITLE
Recurring event exceptions are incompatible with other clients

### ISSUE THREAD

**Issue by DevCybran** [bitfireAT/davdroid#579]
When an exception is added to a recurring event and is being synced to a server by DAVdroid, the exception is not properly reflected on other clients like Owncloud web client and Thunderbird Lightning. The same can be observed the other way around: When an exception is created by Lighning, it is not properly reflected on an Android calendar synced by DAVdroid.

The following software has been used to reproduce the issue:
- Android 4.2.2
- DAVdroid 0.8.1
- Owncloud 8.1
- Lightning 4.0.1

The following problems arise:
**Procedure:** Create an event exception on Android, sync using DAVdroid.
**Outcome:** The exception is not visible in the Owncloud web client, the event is still there. The event is still listed in Lightning with a strike-through effect: 
![davdroid_lighning_error](https://cloud.githubusercontent.com/assets/706324/8762293/2fdf346a-2d75-11e5-93ac-d906ad26929f.png)
**Expected result:** The event should not be visible on the date the exception was made for, neither in Owncloud nor Lightning.

**Procedure:** Create and sync an event exception using Lightning.
**Outcome:** The exception is reflected in the Owncloud web client (the event is gone on that date). On Android+DAVdroid, the event is still present on the date the exception was made for and does not show any kind of alteration.
**Expected result:** The event should not be visible on the date the exception was made for, neither in Owncloud (matches the Outcome above), nor Android (where DAVdroid seems to fail integrating the exception properly).

**Comment by rfc2822** [comment]
> Outcome: The exception is not visible in the Owncloud web client, the event is still there. The event is still listed in Lightning with a strike-through effect:
davdroid_lighning_error
Expected result: The event should not be visible on the date the exception was made for, neither in Owncloud nor Lightning.

This is a behaviour of your calendar app. It doesn't set an EXDATE (meaning that on this day, there's no recurrence) but overrides the specific occurence of this day by "STATUS:CANCELLED" which is then shown as strike-through in Lightning.

DAVdroid has no influence on this, see also: https://twitter.com/davdroidapp/status/527057795980754945

> Procedure: Create and sync an event exception using Lightning.
Outcome: The exception is reflected in the Owncloud web client (the event is gone on that date). On Android+DAVdroid, the event is still present on the date the exception was made for and does not show any kind of alteration.
Expected result: The event should not be visible on the date the exception was made for, neither in Owncloud (matches the Outcome above), nor Android (where DAVdroid seems to fail integrating the exception properly).

It seems that EXDATEs with UTC time zone (`yyyymmddThhmmssZ`) were inserted as local time into the calendar store, which expects either an explizit time zone or UTC with …Z. This has been fixed now.
