### ISSUE TITLE
Some contacts are not synced from Owncloud

### ISSUE THREAD

**Issue by kasiub** [bitfireAT/davdroid#582]
Hello,

Most of my contacts are synced from Owncloud but few are not. I can't find any relation between the contacts which are not synced. The issue should not be related to Owncloud has I used another cardav app before without issue.

Is it possible to collect some logs in order to identify the issue?

Owncloud version: 8.1.0
Davdroid version: 0.8.1 (from fdroid)
Phone: Cyanogen 11 M11

Thanks

**Comment by untitaker** [comment]
https://github.com/bitfireAT/davdroid/issues/578

**Comment by rfc2822** [comment]
I guess that this is a duplicate #578, as @untitaker said. Please follow up there.
