### ISSUE TITLE
cannot add event (birthday) to DAVdroid contact

### ISSUE THREAD

**Issue by tessus** [bitfireAT/davdroid#588]
DAVdroid/0.8.1

When I create a new contact entry on my phone and select DAVdroid contact, I cannot add another field for events (birthday). See screenshot for the fields I can add.

Even though the birthday is present on the server (in my case ownCloud) for a contact and the contact is synced to the device, there's no birthday field on my device for that contact.

![screenshot_2015-07-28-23-52-00](https://cloud.githubusercontent.com/assets/223439/8949792/ea563452-3585-11e5-9f21-6fe68bf5d2a4.png)

**Comment by rfc2822** [comment]
Seems like an issue of your Contacts app. Which app do you use (firmware, version etc)? Can you try another app?

**Comment by tessus** [comment]
I'm using a Samsung S3, Android 4.3 and the stock Contacts app. I realize that this is rather old SW, but the Contacts app can create events like birthdays or anniversaries for Google and device storage.
Doesn't that mean that the app is capable of using that field? In any case, I can try another contacts app, but I wouldn't know which one to try. Any suggestions?

**Comment by untitaker** [comment]
Dmfs has a contacts editor app in the Playstore that is a replacement for such broken stock apps. Perhaps using that fixes your problem.

On 30 July 2015 08:22:37 CEST, "Helmut K. C. Tessarek" <notifications@github.com> wrote:
>I'm using a Samsung S3, Android 4.3 and the stock Contacts app. I
>realize that this is rather old SW, but the Contacts app can create
>events like birthdays or anniversaries for Google and device storage.
>Doesn't that mean that the app is capable of using that field? In any
>case, I can try another contacts app, but I wouldn't know which one to
>try. Any suggestions?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/588#issuecomment-126200323

-- 
Sent from my phone. Please excuse my brevity.

**Comment by tessus** [comment]
@untitaker thanks for the tip. This actually worked. I still don't quite understand why a stock app would limit functionality.

**Comment by rfc2822** [comment]
@tessus I'm sure its a feature ;)

So when this is working for you, I'm closing this issue here.
