### ISSUE TITLE
Loses unsynced data when uninstalled

### ISSUE THREAD

**Issue by dpocock** [bitfireAT/davdroid#589]
When setting up a calendar, I saw the message telling me to uninstall DAVdroid, install the Tasks app and then reinstall DAVdroid

After doing this, I realized that the uninstall removes all unsynced contact data from the phone.

It should probably display a warning encouraging the user to sync their contacts before uninstall.

**Comment by jkufner** [comment]
Why it requires reinstall in the first place?

**Comment by dpocock** [comment]
If the Tasks app is installed after the DAVdroid app, then the DAVdroid app won't have the permissions to interact with the Tasks app.

**Comment by rfc2822** [comment]
I think you can reinstall without uninstalling, and unsynced data should be kept, but I'm not sure.

**Comment by dpocock** [comment]
If I just follow the instructions, unsynced data is lost

**Comment by rfc2822** [comment]
I just wonder, how can you have unsynced data when you don't have set up the account yet?

Can you please given detailed instructions on how to reproduce the issue?

**Comment by dpocock** [comment]
If you don't understand the issue, why did you close it?

The problem occurs if somebody has already been using DAVdroid with their contacts and then one day they realize they can use it for calendar and tasks too

When they start to setup the calendar settings, it tells them to uninstall, install the Tasks app and then re-install DAVdroid.

When the user does the uninstall, any locally unsynced contact data is lost.

**Comment by rfc2822** [comment]
> If you don't understand the issue, why did you close it?

It's closed with a solution. I have updated the instructions so that the user is notified about losing unsynced data when uninstalling DAVdroid (although this is clear for me, but I guess I'm biased).

**Comment by dpocock** [comment]
The user may have the impression that the unsyncned data is owned by the Contacts app rather than Davdroid
