### ISSUE TITLE
sync ambiguity

### ISSUE THREAD

**Issue by dpocock** [bitfireAT/davdroid#591]
If I go into the address book -> menu -> accounts, I see the "Sync" popup and "Auto-sync app data" is not ticked

If I go into DAVdroid using its own launcher icon and go to the settings page, under the Synchronization heading it says "Every 1440 minutes + immediately on local changes"

Is there any reason these different views don't appear to be consistent?

**Comment by rfc2822** [comment]
The system-wide Sync setting is not related to app-specific sync settings. "Auto-sync app data" is a system-wide switch that will be disabled, for instance, in energy-saving mode.

However, when the Sync switch is on, DAVdroid requests syncs every 1440 minutes from the system (note that the system sync manager calls DAVdroid, not vice versa).
