### ISSUE TITLE
Contact pictures not syncing

### ISSUE THREAD

**Issue by steveriley** [bitfireAT/davdroid#592]
A few days ago I switched from CalDAV-Sync and CardDAV-Sync to DAVdroid. Earlier today I created a contact on the phone and added a picture. When the contact syncs to my ownCloud server, the picture disappears. This did not happen with CardDAV-Sync.

The other direction works fine. I can create a contact on ownCloud, add a picture, and it syncs to the phone. I can also create a contact in KDE's KAddressBook, add a picture, and it syncs to the phone.

I see there are some similar issues here about degrading images. I've opened a new issue because, in my case, the image is deleted.

DAVdroid: 0.8.1
ownCloud: 8.1
Android: 4.4.4 (on Samsung Galaxy Note 4)

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

**Comment by rfc2822** [comment]
Seems to be an OwnCloud problem. Please follow up at https://github.com/owncloud/contacts/issues/1011.
