### ISSUE TITLE
Tasks description isn't synced

### ISSUE THREAD

**Issue by jluttine** [bitfireAT/davdroid#595]
It seems that the description field of Tasks isn't synced.

I'm using Tasks, DAVdroid and Owncloud in my setup, so I'm not sure where the problem is but it might be in DAVdroid as suggested by Tasks dev:
https://github.com/dmfs/tasks/issues/156

**Comment by rfc2822** [comment]
I can't reproduce that. Task descriptions are synced correctly here.

Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

**Comment by jluttine** [comment]
Ok, thanks. I'll take a closer look into this. It actually might be something else that's broken because I don't see the problem in a simple case, so I'll close this for now and examine it in more detail.
