### ISSUE TITLE
Grouped contacts sync

### ISSUE THREAD

**Issue by Dark-Fenix** [bitfireAT/davdroid#598]
Hi,
I just upgrade my Xperia SP to Cyanogen 12.1 (Android 5.1) and setup a fresh davdroid sync with my owncloud 8.1 server.
When I try to sync my contacts, I can see all of them for a few seconds in the contacts app, then those in a group disappear. I can't display them even if I modify the display settings (view all contacts or set a custom view). So I only have the non-grouped people.

**Comment by devvv4ever** [comment]
Hi,

you've been affected by an owncloud bug described in #578 . 
You need to change a single line in your owncloud or wait for a new release that has the proposed patch.

**Comment by Dark-Fenix** [comment]
Thx, problem solved. Just waiting for a clean update of owncloud now :)
