### ISSUE TITLE
Support untrusted certificates

### ISSUE THREAD

**Issue by ochurlaud** [bitfireAT/davdroid#602]
I'm using an OVH mutualized host and can't afford to pay for their SSL options. But forcing ssl is still possible which let me use https:// with a default certificate.

It would be great if the app warned "Your certificate is not trusted, do you want to go further?" and allow the "Yes" answer.

Thx !

Awsome app btw.

**Comment by untitaker** [comment]
The solution is to install the certificate in the Android cert store.

**Comment by devvv4ever** [comment]
Please follow up in #3 for more than extensive discussion on this matter ;-)
