### ISSUE TITLE
"Missing capabilities" with Posteo

### ISSUE THREAD

**Issue by mrjovanovic** [bitfireAT/davdroid#604]
I keep getting an error message, trying to add Posteo's service. I'm using DavDroid 0.8.3 from F-Droid, with CyanogenMod M12 (proprietary services removed). The message states "Missing capabilities: Invalid DAV response: No CalDAV-/CardDav services available at this location".

Posteo calendar syncs fine in Evolution on GNU/Linux. 

gist of logcat below:
https://gist.github.com/mrjovanovic/dd49a05059c2d427e2d3#file-davdroid-txt

(I apologize for the first 300 lines, I don't think they are relevant, but I didn't want to exclude anything potentially relevant.)

**Comment by devvv4ever** [comment]
What URL do you try to connect to?

**Comment by mrjovanovic** [comment]
As per the guide on DavDroid's website and Posteo, https://posteo.de:8443

The URL should be in the logs as well.

On August 16, 2015 2:00:45 PM CEST, devvv4ever <notifications@github.com> wrote:
>What URL do you try to connect to?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/604#issuecomment-131531602

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by devvv4ever** [comment]
The URL is correct. The logs show that your proxy rejects the connection you want to establish with posteo.de. You need to fix your settings on the phone.

**Comment by mrjovanovic** [comment]
I thought so too, the only issue is that the proxy (which is from my 
cell carrier) is also the one that Evolution uses, which can easily sync 
with Posteo. Why would Evolution be able to go through the proxy, but 
not DavDroid?

On Sun, Aug 16, 2015 at 07:11:57AM -0700, devvv4ever wrote:
>The URL is correct. The logs show that your proxy rejects the connection you want to establish with posteo.de. You need to fix your settings on the phone.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/604#issuecomment-131554697

-- 
-Milos

**Comment by devvv4ever** [comment]
If you use your internet via usb tethering from your phone, is evolution still able to sync?

Nevertheless, I don't think DAVdroid is making problems in this case, at least thats what the logs say...

Probably the CM privacy guard is active?

**Comment by mrjovanovic** [comment]
Yes, thats exactly true. Using phone on tethering, Evolution syncs fine. Privacy Guard is off for DavDroid. I'm at a loss how to debug this further... Thanks for your help. :)

On August 16, 2015 10:17:35 PM CEST, devvv4ever <notifications@github.com> wrote:
>If you use your internet via usb tethering from your phone, is
>evolution still able to sync?
>
>Nevertheless, I don't think DAVdroid is making problems in this case,
>at least thats what the logs say...
>
>Probably the CM privacy guard is active?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/604#issuecomment-131617606

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrjovanovic** [comment]
Can confirm, the issue goes away on WiFi. I'm still unclear why the mobile provider would block DavDroid's connections, but not Evolution's over the same connection. Do they use a different protocol? It's even stranger since I could access https://posteo.de:8443/calendars/username/default over the stock browser on the device.

Appreciate the help, sorry for the noise.
