### ISSUE TITLE
Calendar colors

### ISSUE THREAD

**Issue by hitam4450** [bitfireAT/davdroid#614]
During establishing a sync calendar it is not possible to select a special color for the calendar.
Color will be randomly selected by the process. No change of color  afterwards possible.

regards, hitam4450

**Comment by untitaker** [comment]
The color is fetched from the server.

**Comment by devvv4ever** [comment]
hitam4450: there is definitely no randomness. if you want to change it, you need to log in to you web-interface of the server and change the color there. the set color is synchronized at next time when DAVdroid tries to get data from the server. or you can manually force a sync in the account settings.
