### ISSUE TITLE
contact photo gets deleted after update on android device on sync with owncloud

### ISSUE THREAD

**Issue by martingwb** [bitfireAT/davdroid#616]
Environment:
DAVdroid 0.8.3
owncloud: 8.1.1 on raspbian, 
cyanogenmod 5.1.1, google contacts app
photo: jpeg, 5.3k, 234x216

How to reproduce:
- insert a contact on android device with photo
- start a sync process on the android device

Result: the photo disappears on android device, the contact is transferred to oc but without a photo - not ok
- add photo to contact on oc
- start a sync process on the android device

Result: the photo appears on the android device - ok
- start another sync on the android device

Result: photo still ok on android device and oc - ok
- modify the contact on the android device
- start a sync process on the android device

Result: the photo disappears on android device, the photo disappears on oc - not ok

Expected result: contact photos not disappearing
Let me know what further information you need.

**Comment by devvv4ever** [comment]
Thank you for the report.However this is a bug in OC whch has to do with asomehow weird format of saving image data. Please follow up there:

https://github.com/owncloud/contacts/issues/994
