### ISSUE TITLE
CTag is not changing after changing my contact informartion

### ISSUE THREAD

**Issue by unnivm** [bitfireAT/davdroid#617]
Hi,

I have developed a service that will process Carddav request and responses. I was able to add a new Carddav account. So after creating a new account, I modified my local contacts on android. It is trying to sync with my server though. But I am seeing a message saying '''Last Local cTag = e12345. current remote tag = e12345'''

I have assigned a value to e12345 for Ctag. Now my question is once I change the contact information,  Ctag is also supposed to be changed to a new value on Android. But this is not happening, it seems. Am I correct?

Please let me know if I am missing any steps here.

Thanks,

Unni

**Comment by untitaker** [comment]
The important thing is that the data gets synchronized. Does it?

**Comment by devvv4ever** [comment]
The "local ctag" actually is the "last known remote ctag". It's not supposed to change on local modifications (those are managed using DIRTY flags). The message you've got means that since last sync the server ctag didn't change.

Do you see a problem somewhere?

**Comment by unnivm** [comment]
OK. then let me tell you my use case:


   - I was able to add an account.
   -
   - There are *no contacts* currently on my server.
   -
   - In the whole process a cTag has been generated with the value
   mentioned above.
   -
   - Now , I modified a contact on Android side


This change is triggered the app to sync with my server with the above
 message.

Now in this scenario, how the app is pushing changes to the server. My
understanding is CTAG is being modified by the app on client side in order
to push the changes. If the CTAG is not modified, the app is not pushing
the changes. Also, the contact I modified is not there on server.

Please correct my understanding and what steps need to be looked into in
order to achieve this.

Yours Sincerely,
Unni






On Fri, Aug 21, 2015 at 4:38 AM, devvv4ever <notifications@github.com>
wrote:

> The "local ctag" actually is the "last known remote ctag". It's not
> supposed to change on local modifications (those are managed using DIRTY
> flags). The message you've got means that since last sync the server ctag
> didn't change.
>
> Do you see a problem somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitfireAT/davdroid/issues/617#issuecomment-133207849>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by unnivm** [comment]
Hi Markus,

In this use case, I do not think the data is  *Sync* with the server. Let
me add couple of points here. I added an account and selected that account
with my *contacts* for sync. But I am not sure the changes are pushed to
server for the first time as I am not getting any error nor requests either
in app log or in my server.

So please correct me if I am doing wrong.

Yours Sincerely,
Unni



On Fri, Aug 21, 2015 at 1:45 AM, Markus Unterwaditzer <
notifications@github.com> wrote:

> The important thing is that the data gets synchronized. Does it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitfireAT/davdroid/issues/617#issuecomment-133158452>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by unnivm** [comment]
Hi Markus,

This can be closed now as I happened to see the changes in my server when
the app was "syncing " my contact details. The reason was the sync interval
is very large value. Now I changed to "manual" so that whenever I updated
my contact details, I will sync it manually.

However, one small clarification.
At the time of  adding  a new account, can I get the contacts from the
server?

Thank you for your co-operation,

Yours Sincerely,
Unni V Mana



On Fri, Aug 21, 2015 at 11:38 AM, unni mana <unnivm@gmail.com> wrote:

> Hi Markus,
>
> In this use case, I do not think the data is  *Sync* with the server. Let
> me add couple of points here. I added an account and selected that account
> with my *contacts* for sync. But I am not sure the changes are pushed to
> server for the first time as I am not getting any error nor requests either
> in app log or in my server.
>
> So please correct me if I am doing wrong.
>
> Yours Sincerely,
> Unni
>
>
>
> On Fri, Aug 21, 2015 at 1:45 AM, Markus Unterwaditzer <
> notifications@github.com> wrote:
>
>> The important thing is that the data gets synchronized. Does it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitfireAT/davdroid/issues/617#issuecomment-133158452>
>> .
>>
>
>
>
> --
> ---
> If not played, Free Sudoku Android Game
> <https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by untitaker** [comment]
@unnivm You can close issues yourself, next to the submit button of the comment
form.
