### ISSUE TITLE
Crash when syncing contacts

### ISSUE THREAD

**Issue by jobnoorman** [bitfireAT/davdroid#622]
I'm getting the following crash whenever I try to sync contacts:

> E/AndroidRuntime( 7957): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime( 7957): Process: at.bitfire.davdroid:sync, PID: 7957
E/AndroidRuntime( 7957): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.resource.LocalAddressBook.populateIMPP(LocalAddressBook.java:433)
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.resource.LocalAddressBook.populate(LocalAddressBook.java:214)
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.resource.LocalCollection.findById(LocalCollection.java:220)
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.syncadapter.SyncManager.pushDirty(SyncManager.java:170)
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:56)
E/AndroidRuntime( 7957):        at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:138)
E/AndroidRuntime( 7957):        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

Please let me know if (and how) I can provide more useful information.

**Comment by rfc2822** [comment]
This seems to be for an old DAVdroid version. Which version do you use?

**Comment by jobnoorman** [comment]
I just updated to 0.8.4 this morning. The crash report is from after the update but I was already experiencing crashes before.

**Comment by rfc2822** [comment]
Are you sure that the crash report is from after the update? The line numbers don't seem to match to 0.8.4, and this bug should have been fixed.

Can you please uninstall DAVdroid, re-install 0.8.4 and then try again?

If the problem persists, it's a problem with an IMPP line. Then please provide [verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs) and the VCard where the issue occurs.

**Comment by jobnoorman** [comment]
This is weird: reinstalling DAVdroid didn't help but removing en re-adding the offending sync account did. Everything seems to be working OK now!
