### ISSUE TITLE
apache http client deprecated

### ISSUE THREAD

**Issue by aminmazi** [bitfireAT/davdroid#630]
since apache is deprecated in android api >=22, is it possible to migrate to another framework (like volley) for http requests?

**Comment by rfc2822** [comment]
DAVdroid doesn't use the Apache lib of Android, but [an one one](https://github.com/bitfireAT/davdroid/tree/master/lib/httpclient-android) which is not deprecated.

**Comment by aminmazi** [comment]
thank you, I was using latest version of Apache  lib that was deprecated, not the ported version for android!

**Comment by aminmazi** [comment]
I tried to compile project with android sdk version 23 and build failed due to some errors in http classes
I changed this lines in app build.gradle file:
```
android {
    compileSdkVersion 23
    buildToolsVersion '23'

    defaultConfig {
        applicationId "at.bitfire.davdroid"
        minSdkVersion 14
        targetSdkVersion 23
    }
```
and this lines in httpclient module build.gradle:
```
android {
    // SDK versions and compileOptions adapted to DAVdroid needs
    compileSdkVersion 23
    buildToolsVersion '23'
    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 23
    }
```
what if we want to target android 6.0 (marshmallow) sdk version?
