### ISSUE TITLE
Sync "works" but then most of the contact are removed...

### ISSUE THREAD

**Issue by callmemagnus** [bitfireAT/davdroid#631]
I'm a bit puzzled. Synchro works but then removes the contacts from the storage.

# context

First some data:
- DAVdroid 0.8.4 from F-Droid
- owncloud 8.1 (318 contact on my contact app in owncloud)
- android 5.1.1 (Xiaomi Mi3 XenonHD ROM)

On roundcube, I use a plugin to retrieve the contact from owncloud via carddav and the result is 318 contacts. I tried to purge the db on roundcube and sync again; still 318 contacts.

# the issue: android sync

I sadly don't know since what or when, but I experience a strange issue on my android device: 

1. I purge the contact storage app (I even uninstalled davdroid, rebooted and reinstalled)
2. go to contact app
3. select my davdroid account to be the only visible
4. start manual sync
5. it syncs (see below): i.e. contact are added
6. then only a few remains in the contact db

It does a lot of stuff; requesting vcards, obtaining them and consuming them. 
While sync, If I switch to the contact app, I see the list of contacts is growing (with all the entries as some disappear latter).

In the log in the end I have
```
08-29 11:34:33.379 I/davdroid.SyncManager(23059): Removing entries that are not present remotely anymore (retaining 318 entries)
```

But in the end I only have 22 contacts in the app and the db.

I pull the contact2.db from my phone and it contains 22 entries related to the account "owncloud".

If I look at the deleted_contact table, it contains 303 entries.

I don't know if this is a davdroid bug but it seems to not persist the changes (although changes are persisted but then deleted...).

Is there anything I can do to help diagnose this ?

I produced a log based on your recommendation checked it for relevant info, but no errors. 
I'm unable to add it here as it is more than 700k.

Thanks in advance for any hints.

**Comment by callmemagnus** [comment]
me again, I just checked out the code and ran it on the emulator with the same account on the same server and I got the same result...

I checked the server, not errors and all the contact are retrieved.

I'll debug a little to see if it occurs in davdroid or not.

**Comment by akki42** [comment]
Hi,
to me this looks like yet another duplicate of https://github.com/bitfireAT/davdroid/issues/578 , i.e. a bug in owncloud's current contacts app.

That thread includes two possible workarounds ( https://github.com/bitfireAT/davdroid/issues/578#issuecomment-126699251 and https://github.com/bitfireAT/davdroid/issues/578#issuecomment-130668178 ).

A patch for the calendar app has been submitted (https://github.com/owncloud/contacts/issues/581), but I don't know when to expect a new release.

**Comment by callmemagnus** [comment]
yeah you're right...

I checked the amount of entries on owncloud that do not have a @ in the UID and the count is correct.

I'm removing the @ of the uid in the meantime. Thanks!
